// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/ffmpeg.dart';
import 'api/hardware.dart';
import 'api/models.dart';
import 'api/qwen.dart';
import 'api/silero_vad.dart';
import 'api/simple.dart';
import 'api/stream_pipeline.dart';
import 'api/subtitle_split.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'qwen/backend.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 2035100308;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_audio2srt',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<List<(BigInt, BigInt)>>
  crateApiSileroVadSileroVadEngineDetectSpeechSegments({
    required SileroVadEngine that,
    required List<double> samples,
    required int minSpeechMs,
    required int minSilenceMs,
    required double threshold,
  });

  Future<SileroVadEngine> crateApiSileroVadSileroVadEngineLoad({
    required String vadModelPath,
  });

  void crateApiStreamPipelineCancelTranscriptionBackend();

  Future<String> crateApiSileroVadConvertChinese({
    required String text,
    required bool toSimplified,
  });

  Future<List<String>> crateApiSileroVadConvertChineseList({
    required List<String> texts,
    required bool toSimplified,
  });

  Future<(String, String)> crateApiFfmpegConvertIso6392({required String code});

  Stream<FfmpegEvent> crateApiFfmpegExtractAudioFromMedia({
    required String ffmpegPath,
    required String inputPath,
    required String outputPath,
  });

  Future<HardwareAccelerationInfo>
  crateApiSileroVadGetHardwareAccelerationInfo();

  Future<QwenHardwareInfo> crateApiHardwareGetQwenHardwareInfo();

  Future<QwenHardwareInfo> crateApiQwenGetQwenRuntimeInfo();

  Future<QwenRuntimeStatus?> crateApiStreamPipelineGetQwenRuntimeStatus();

  String crateApiSimpleGreet({required String name});

  Future<HardwareAccelerationInfo>
  crateApiSileroVadHardwareAccelerationInfoDefault();

  Future<void> crateApiSimpleInitApp();

  Stream<FfmpegEvent> crateApiFfmpegMuxSrtToVideo({
    required String ffmpegPath,
    required String videoPath,
    required String srtPath,
    required String outputPath,
    required bool hardBurn,
  });

  void crateApiStreamPipelinePreloadQwenModel({
    required String asrModelDir,
    String? alignerModelDir,
    String? decoderFile,
    required EncoderBackend encoderBackend,
    required DecoderBackend decoderBackend,
  });

  Future<List<AudioTrackInfo>> crateApiFfmpegProbeAudioTracks({
    required String ffmpegPath,
    required String filePath,
  });

  Future<void> crateApiSileroVadRegisterThreadAsProAudio();

  void crateApiStreamPipelineSetRustPerfLogging({required bool enable});

  Future<List<TranscriptionSegment>> crateApiSubtitleSplitSplitSubtitles({
    required List<WordItem> units,
    required String quality,
    required PlatformInt64 blockStartMs,
    required PlatformInt64 blockEndMs,
  });

  Stream<TranscriptionEvent> crateApiSileroVadTranscribe({
    required String modelPath,
    required String vadModelPath,
    required String audioPath,
    String? language,
    required bool translate,
    int? threads,
    required bool useGpu,
    required bool vadEnabled,
    required double vadThreshold,
    required int vadMinSpeechMs,
    required int vadMinSilenceMs,
    required double temperature,
    required double temperatureInc,
    required double entropyThold,
    required double logprobThold,
    required double noSpeechThold,
    required bool noContext,
    required bool noStateHistory,
  });

  Stream<TranscriptionEvent> crateApiStreamPipelineTranscribeStream({
    required PipelineConfig config,
  });

  Future<TranscriptionSegment> crateApiSileroVadTranscriptionSegmentDefault();

  Future<void> crateApiQwenUnloadQwenRuntime();

  void crateApiStreamPipelineUnloadQwenRuntime();

  Future<ModelInfo> crateApiModelsValidateQwenModel({required String modelDir});

  Future<ModelInfo> crateApiQwenValidateQwenModelDir({
    required String modelDir,
  });

  Future<VulkanDeviceInfo> crateApiSileroVadVulkanDeviceInfoDefault();

  Future<void> crateApiQwenWarmupQwenRuntime({
    required QwenWarmupConfig config,
  });

  Future<void> crateApiSileroVadWarmupWhisperContext({
    required String modelPath,
    required bool useGpu,
    required double totalDuration,
  });

  Future<WordItem> crateApiSileroVadWordItemDefault();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SileroVadEngine;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SileroVadEngine;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SileroVadEnginePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<List<(BigInt, BigInt)>>
  crateApiSileroVadSileroVadEngineDetectSpeechSegments({
    required SileroVadEngine that,
    required List<double> samples,
    required int minSpeechMs,
    required int minSilenceMs,
    required double threshold,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSileroVadEngine(
            that,
            serializer,
          );
          sse_encode_list_prim_f_32_loose(samples, serializer);
          sse_encode_i_32(minSpeechMs, serializer);
          sse_encode_i_32(minSilenceMs, serializer);
          sse_encode_f_32(threshold, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_record_usize_usize,
          decodeErrorData: sse_decode_String,
        ),
        constMeta:
            kCrateApiSileroVadSileroVadEngineDetectSpeechSegmentsConstMeta,
        argValues: [that, samples, minSpeechMs, minSilenceMs, threshold],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSileroVadSileroVadEngineDetectSpeechSegmentsConstMeta =>
      const TaskConstMeta(
        debugName: "SileroVadEngine_detect_speech_segments",
        argNames: [
          "that",
          "samples",
          "minSpeechMs",
          "minSilenceMs",
          "threshold",
        ],
      );

  @override
  Future<SileroVadEngine> crateApiSileroVadSileroVadEngineLoad({
    required String vadModelPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(vadModelPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSileroVadEngine,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSileroVadSileroVadEngineLoadConstMeta,
        argValues: [vadModelPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSileroVadSileroVadEngineLoadConstMeta =>
      const TaskConstMeta(
        debugName: "SileroVadEngine_load",
        argNames: ["vadModelPath"],
      );

  @override
  void crateApiStreamPipelineCancelTranscriptionBackend() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStreamPipelineCancelTranscriptionBackendConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiStreamPipelineCancelTranscriptionBackendConstMeta =>
      const TaskConstMeta(
        debugName: "cancel_transcription_backend",
        argNames: [],
      );

  @override
  Future<String> crateApiSileroVadConvertChinese({
    required String text,
    required bool toSimplified,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          sse_encode_bool(toSimplified, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSileroVadConvertChineseConstMeta,
        argValues: [text, toSimplified],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSileroVadConvertChineseConstMeta =>
      const TaskConstMeta(
        debugName: "convert_chinese",
        argNames: ["text", "toSimplified"],
      );

  @override
  Future<List<String>> crateApiSileroVadConvertChineseList({
    required List<String> texts,
    required bool toSimplified,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(texts, serializer);
          sse_encode_bool(toSimplified, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSileroVadConvertChineseListConstMeta,
        argValues: [texts, toSimplified],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSileroVadConvertChineseListConstMeta =>
      const TaskConstMeta(
        debugName: "convert_chinese_list",
        argNames: ["texts", "toSimplified"],
      );

  @override
  Future<(String, String)> crateApiFfmpegConvertIso6392({
    required String code,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(code, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_record_string_string,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFfmpegConvertIso6392ConstMeta,
        argValues: [code],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfmpegConvertIso6392ConstMeta =>
      const TaskConstMeta(debugName: "convert_iso639_2", argNames: ["code"]);

  @override
  Stream<FfmpegEvent> crateApiFfmpegExtractAudioFromMedia({
    required String ffmpegPath,
    required String inputPath,
    required String outputPath,
  }) {
    final sink = RustStreamSink<FfmpegEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_ffmpeg_event_Sse(sink, serializer);
            sse_encode_String(ffmpegPath, serializer);
            sse_encode_String(inputPath, serializer);
            sse_encode_String(outputPath, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 8,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiFfmpegExtractAudioFromMediaConstMeta,
          argValues: [sink, ffmpegPath, inputPath, outputPath],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiFfmpegExtractAudioFromMediaConstMeta =>
      const TaskConstMeta(
        debugName: "extract_audio_from_media",
        argNames: ["sink", "ffmpegPath", "inputPath", "outputPath"],
      );

  @override
  Future<HardwareAccelerationInfo>
  crateApiSileroVadGetHardwareAccelerationInfo() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_hardware_acceleration_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSileroVadGetHardwareAccelerationInfoConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSileroVadGetHardwareAccelerationInfoConstMeta =>
      const TaskConstMeta(
        debugName: "get_hardware_acceleration_info",
        argNames: [],
      );

  @override
  Future<QwenHardwareInfo> crateApiHardwareGetQwenHardwareInfo() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_qwen_hardware_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHardwareGetQwenHardwareInfoConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHardwareGetQwenHardwareInfoConstMeta =>
      const TaskConstMeta(debugName: "get_qwen_hardware_info", argNames: []);

  @override
  Future<QwenHardwareInfo> crateApiQwenGetQwenRuntimeInfo() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_qwen_hardware_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiQwenGetQwenRuntimeInfoConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQwenGetQwenRuntimeInfoConstMeta =>
      const TaskConstMeta(debugName: "get_qwen_runtime_info", argNames: []);

  @override
  Future<QwenRuntimeStatus?> crateApiStreamPipelineGetQwenRuntimeStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_qwen_runtime_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStreamPipelineGetQwenRuntimeStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStreamPipelineGetQwenRuntimeStatusConstMeta =>
      const TaskConstMeta(debugName: "get_qwen_runtime_status", argNames: []);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<HardwareAccelerationInfo>
  crateApiSileroVadHardwareAccelerationInfoDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_hardware_acceleration_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSileroVadHardwareAccelerationInfoDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSileroVadHardwareAccelerationInfoDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "hardware_acceleration_info_default",
        argNames: [],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Stream<FfmpegEvent> crateApiFfmpegMuxSrtToVideo({
    required String ffmpegPath,
    required String videoPath,
    required String srtPath,
    required String outputPath,
    required bool hardBurn,
  }) {
    final sink = RustStreamSink<FfmpegEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_ffmpeg_event_Sse(sink, serializer);
            sse_encode_String(ffmpegPath, serializer);
            sse_encode_String(videoPath, serializer);
            sse_encode_String(srtPath, serializer);
            sse_encode_String(outputPath, serializer);
            sse_encode_bool(hardBurn, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 16,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiFfmpegMuxSrtToVideoConstMeta,
          argValues: [
            sink,
            ffmpegPath,
            videoPath,
            srtPath,
            outputPath,
            hardBurn,
          ],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiFfmpegMuxSrtToVideoConstMeta =>
      const TaskConstMeta(
        debugName: "mux_srt_to_video",
        argNames: [
          "sink",
          "ffmpegPath",
          "videoPath",
          "srtPath",
          "outputPath",
          "hardBurn",
        ],
      );

  @override
  void crateApiStreamPipelinePreloadQwenModel({
    required String asrModelDir,
    String? alignerModelDir,
    String? decoderFile,
    required EncoderBackend encoderBackend,
    required DecoderBackend decoderBackend,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(asrModelDir, serializer);
          sse_encode_opt_String(alignerModelDir, serializer);
          sse_encode_opt_String(decoderFile, serializer);
          sse_encode_encoder_backend(encoderBackend, serializer);
          sse_encode_decoder_backend(decoderBackend, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStreamPipelinePreloadQwenModelConstMeta,
        argValues: [
          asrModelDir,
          alignerModelDir,
          decoderFile,
          encoderBackend,
          decoderBackend,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStreamPipelinePreloadQwenModelConstMeta =>
      const TaskConstMeta(
        debugName: "preload_qwen_model",
        argNames: [
          "asrModelDir",
          "alignerModelDir",
          "decoderFile",
          "encoderBackend",
          "decoderBackend",
        ],
      );

  @override
  Future<List<AudioTrackInfo>> crateApiFfmpegProbeAudioTracks({
    required String ffmpegPath,
    required String filePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(ffmpegPath, serializer);
          sse_encode_String(filePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_audio_track_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFfmpegProbeAudioTracksConstMeta,
        argValues: [ffmpegPath, filePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFfmpegProbeAudioTracksConstMeta =>
      const TaskConstMeta(
        debugName: "probe_audio_tracks",
        argNames: ["ffmpegPath", "filePath"],
      );

  @override
  Future<void> crateApiSileroVadRegisterThreadAsProAudio() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSileroVadRegisterThreadAsProAudioConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSileroVadRegisterThreadAsProAudioConstMeta =>
      const TaskConstMeta(
        debugName: "register_thread_as_pro_audio",
        argNames: [],
      );

  @override
  void crateApiStreamPipelineSetRustPerfLogging({required bool enable}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(enable, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStreamPipelineSetRustPerfLoggingConstMeta,
        argValues: [enable],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStreamPipelineSetRustPerfLoggingConstMeta =>
      const TaskConstMeta(
        debugName: "set_rust_perf_logging",
        argNames: ["enable"],
      );

  @override
  Future<List<TranscriptionSegment>> crateApiSubtitleSplitSplitSubtitles({
    required List<WordItem> units,
    required String quality,
    required PlatformInt64 blockStartMs,
    required PlatformInt64 blockEndMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_word_item(units, serializer);
          sse_encode_String(quality, serializer);
          sse_encode_i_64(blockStartMs, serializer);
          sse_encode_i_64(blockEndMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_transcription_segment,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSubtitleSplitSplitSubtitlesConstMeta,
        argValues: [units, quality, blockStartMs, blockEndMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSubtitleSplitSplitSubtitlesConstMeta =>
      const TaskConstMeta(
        debugName: "split_subtitles",
        argNames: ["units", "quality", "blockStartMs", "blockEndMs"],
      );

  @override
  Stream<TranscriptionEvent> crateApiSileroVadTranscribe({
    required String modelPath,
    required String vadModelPath,
    required String audioPath,
    String? language,
    required bool translate,
    int? threads,
    required bool useGpu,
    required bool vadEnabled,
    required double vadThreshold,
    required int vadMinSpeechMs,
    required int vadMinSilenceMs,
    required double temperature,
    required double temperatureInc,
    required double entropyThold,
    required double logprobThold,
    required double noSpeechThold,
    required bool noContext,
    required bool noStateHistory,
  }) {
    final sink = RustStreamSink<TranscriptionEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_transcription_event_Sse(sink, serializer);
            sse_encode_String(modelPath, serializer);
            sse_encode_String(vadModelPath, serializer);
            sse_encode_String(audioPath, serializer);
            sse_encode_opt_String(language, serializer);
            sse_encode_bool(translate, serializer);
            sse_encode_opt_box_autoadd_i_32(threads, serializer);
            sse_encode_bool(useGpu, serializer);
            sse_encode_bool(vadEnabled, serializer);
            sse_encode_f_32(vadThreshold, serializer);
            sse_encode_i_32(vadMinSpeechMs, serializer);
            sse_encode_i_32(vadMinSilenceMs, serializer);
            sse_encode_f_32(temperature, serializer);
            sse_encode_f_32(temperatureInc, serializer);
            sse_encode_f_32(entropyThold, serializer);
            sse_encode_f_32(logprobThold, serializer);
            sse_encode_f_32(noSpeechThold, serializer);
            sse_encode_bool(noContext, serializer);
            sse_encode_bool(noStateHistory, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 22,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiSileroVadTranscribeConstMeta,
          argValues: [
            sink,
            modelPath,
            vadModelPath,
            audioPath,
            language,
            translate,
            threads,
            useGpu,
            vadEnabled,
            vadThreshold,
            vadMinSpeechMs,
            vadMinSilenceMs,
            temperature,
            temperatureInc,
            entropyThold,
            logprobThold,
            noSpeechThold,
            noContext,
            noStateHistory,
          ],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSileroVadTranscribeConstMeta =>
      const TaskConstMeta(
        debugName: "transcribe",
        argNames: [
          "sink",
          "modelPath",
          "vadModelPath",
          "audioPath",
          "language",
          "translate",
          "threads",
          "useGpu",
          "vadEnabled",
          "vadThreshold",
          "vadMinSpeechMs",
          "vadMinSilenceMs",
          "temperature",
          "temperatureInc",
          "entropyThold",
          "logprobThold",
          "noSpeechThold",
          "noContext",
          "noStateHistory",
        ],
      );

  @override
  Stream<TranscriptionEvent> crateApiStreamPipelineTranscribeStream({
    required PipelineConfig config,
  }) {
    final sink = RustStreamSink<TranscriptionEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_transcription_event_Sse(sink, serializer);
            sse_encode_box_autoadd_pipeline_config(config, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 23,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiStreamPipelineTranscribeStreamConstMeta,
          argValues: [sink, config],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiStreamPipelineTranscribeStreamConstMeta =>
      const TaskConstMeta(
        debugName: "transcribe_stream",
        argNames: ["sink", "config"],
      );

  @override
  Future<TranscriptionSegment> crateApiSileroVadTranscriptionSegmentDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_transcription_segment,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSileroVadTranscriptionSegmentDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSileroVadTranscriptionSegmentDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "transcription_segment_default",
        argNames: [],
      );

  @override
  Future<void> crateApiQwenUnloadQwenRuntime() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiQwenUnloadQwenRuntimeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQwenUnloadQwenRuntimeConstMeta =>
      const TaskConstMeta(debugName: "unload_qwen_runtime", argNames: []);

  @override
  void crateApiStreamPipelineUnloadQwenRuntime() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStreamPipelineUnloadQwenRuntimeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStreamPipelineUnloadQwenRuntimeConstMeta =>
      const TaskConstMeta(debugName: "unload_qwen_runtime", argNames: []);

  @override
  Future<ModelInfo> crateApiModelsValidateQwenModel({
    required String modelDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(modelDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_model_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiModelsValidateQwenModelConstMeta,
        argValues: [modelDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelsValidateQwenModelConstMeta =>
      const TaskConstMeta(
        debugName: "validate_qwen_model",
        argNames: ["modelDir"],
      );

  @override
  Future<ModelInfo> crateApiQwenValidateQwenModelDir({
    required String modelDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(modelDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_model_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiQwenValidateQwenModelDirConstMeta,
        argValues: [modelDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQwenValidateQwenModelDirConstMeta =>
      const TaskConstMeta(
        debugName: "validate_qwen_model_dir",
        argNames: ["modelDir"],
      );

  @override
  Future<VulkanDeviceInfo> crateApiSileroVadVulkanDeviceInfoDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_vulkan_device_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSileroVadVulkanDeviceInfoDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSileroVadVulkanDeviceInfoDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "vulkan_device_info_default",
        argNames: [],
      );

  @override
  Future<void> crateApiQwenWarmupQwenRuntime({
    required QwenWarmupConfig config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_qwen_warmup_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiQwenWarmupQwenRuntimeConstMeta,
        argValues: [config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQwenWarmupQwenRuntimeConstMeta =>
      const TaskConstMeta(
        debugName: "warmup_qwen_runtime",
        argNames: ["config"],
      );

  @override
  Future<void> crateApiSileroVadWarmupWhisperContext({
    required String modelPath,
    required bool useGpu,
    required double totalDuration,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(modelPath, serializer);
          sse_encode_bool(useGpu, serializer);
          sse_encode_f_64(totalDuration, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSileroVadWarmupWhisperContextConstMeta,
        argValues: [modelPath, useGpu, totalDuration],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSileroVadWarmupWhisperContextConstMeta =>
      const TaskConstMeta(
        debugName: "warmup_whisper_context",
        argNames: ["modelPath", "useGpu", "totalDuration"],
      );

  @override
  Future<WordItem> crateApiSileroVadWordItemDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_word_item,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSileroVadWordItemDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSileroVadWordItemDefaultConstMeta =>
      const TaskConstMeta(debugName: "word_item_default", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SileroVadEngine => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSileroVadEngine;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SileroVadEngine => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSileroVadEngine;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  SileroVadEngine
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSileroVadEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SileroVadEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SileroVadEngine
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSileroVadEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SileroVadEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SileroVadEngine
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSileroVadEngine(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SileroVadEngineImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<FfmpegEvent> dco_decode_StreamSink_ffmpeg_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<TranscriptionEvent>
  dco_decode_StreamSink_transcription_event_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  TranscriptionSink dco_decode_TraitDef_TranscriptionSink(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  AudioTrackInfo dco_decode_audio_track_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return AudioTrackInfo(
      index: dco_decode_usize(arr[0]),
      codecName: dco_decode_String(arr[1]),
      language: dco_decode_opt_String(arr[2]),
      title: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PipelineConfig dco_decode_box_autoadd_pipeline_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_pipeline_config(raw);
  }

  @protected
  QwenRuntimeStatus dco_decode_box_autoadd_qwen_runtime_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_qwen_runtime_status(raw);
  }

  @protected
  QwenWarmupConfig dco_decode_box_autoadd_qwen_warmup_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_qwen_warmup_config(raw);
  }

  @protected
  TranscriptionEvent dco_decode_box_autoadd_transcription_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_transcription_event(raw);
  }

  @protected
  TranscriptionSegment dco_decode_box_autoadd_transcription_segment(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_transcription_segment(raw);
  }

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_usize(raw);
  }

  @protected
  ComputeDeviceInfo dco_decode_compute_device_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ComputeDeviceInfo(
      name: dco_decode_String(arr[0]),
      vendor: dco_decode_String(arr[1]),
      vramMb: dco_decode_u_64(arr[2]),
      supportsVulkan: dco_decode_bool(arr[3]),
      supportsDirectml: dco_decode_bool(arr[4]),
    );
  }

  @protected
  DecoderBackend dco_decode_decoder_backend(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DecoderBackend.values[raw as int];
  }

  @protected
  EncoderBackend dco_decode_encoder_backend(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return EncoderBackend.values[raw as int];
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FfmpegEvent dco_decode_ffmpeg_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FfmpegEvent(
      progress: dco_decode_opt_box_autoadd_i_32(arr[0]),
      success: dco_decode_opt_String(arr[1]),
      error: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  HardwareAccelerationInfo dco_decode_hardware_acceleration_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return HardwareAccelerationInfo(
      isVulkanAvailable: dco_decode_bool(arr[0]),
      devices: dco_decode_list_vulkan_device_info(arr[1]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<AudioTrackInfo> dco_decode_list_audio_track_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_audio_track_info).toList();
  }

  @protected
  List<ComputeDeviceInfo> dco_decode_list_compute_device_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_compute_device_info).toList();
  }

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<double>;
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(BigInt, BigInt)> dco_decode_list_record_usize_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_usize_usize).toList();
  }

  @protected
  List<TranscriptionSegment> dco_decode_list_transcription_segment(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_transcription_segment)
        .toList();
  }

  @protected
  List<VulkanDeviceInfo> dco_decode_list_vulkan_device_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_vulkan_device_info).toList();
  }

  @protected
  List<WordItem> dco_decode_list_word_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_word_item).toList();
  }

  @protected
  ModelInfo dco_decode_model_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ModelInfo(
      modelId: dco_decode_String(arr[0]),
      path: dco_decode_String(arr[1]),
      valid: dco_decode_bool(arr[2]),
      totalSizeBytes: dco_decode_u_64(arr[3]),
      missingFiles: dco_decode_list_String(arr[4]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  QwenRuntimeStatus? dco_decode_opt_box_autoadd_qwen_runtime_status(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_qwen_runtime_status(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_usize(raw);
  }

  @protected
  PipelineConfig dco_decode_pipeline_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 25)
      throw Exception('unexpected arr length: expect 25 but see ${arr.length}');
    return PipelineConfig(
      ffmpegPath: dco_decode_String(arr[0]),
      inputPath: dco_decode_String(arr[1]),
      modelPath: dco_decode_String(arr[2]),
      vadModelPath: dco_decode_String(arr[3]),
      dfModelPath: dco_decode_String(arr[4]),
      asrModelDir: dco_decode_String(arr[5]),
      alignerModelDir: dco_decode_opt_String(arr[6]),
      decoderFile: dco_decode_opt_String(arr[7]),
      contextPrompt: dco_decode_opt_String(arr[8]),
      encoderBackend: dco_decode_encoder_backend(arr[9]),
      decoderBackend: dco_decode_decoder_backend(arr[10]),
      timestampMode: dco_decode_timestamp_mode(arr[11]),
      language: dco_decode_opt_String(arr[12]),
      translate: dco_decode_bool(arr[13]),
      threads: dco_decode_opt_box_autoadd_i_32(arr[14]),
      useGpu: dco_decode_bool(arr[15]),
      toSimplified: dco_decode_bool(arr[16]),
      noContext: dco_decode_bool(arr[17]),
      noStateHistory: dco_decode_bool(arr[18]),
      enableDenoise: dco_decode_bool(arr[19]),
      vadEnabled: dco_decode_bool(arr[20]),
      vadThreshold: dco_decode_f_64(arr[21]),
      vadMinSpeechMs: dco_decode_i_32(arr[22]),
      vadMinSilenceMs: dco_decode_i_32(arr[23]),
      selectedAudioTrack: dco_decode_opt_box_autoadd_usize(arr[24]),
    );
  }

  @protected
  QwenHardwareInfo dco_decode_qwen_hardware_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return QwenHardwareInfo(
      vulkanAvailable: dco_decode_bool(arr[0]),
      directmlAvailable: dco_decode_bool(arr[1]),
      cudaAvailable: dco_decode_bool(arr[2]),
      cpuAvailable: dco_decode_bool(arr[3]),
      devices: dco_decode_list_compute_device_info(arr[4]),
      recommendedEncoderBackend: dco_decode_encoder_backend(arr[5]),
      recommendedDecoderBackend: dco_decode_decoder_backend(arr[6]),
    );
  }

  @protected
  QwenRuntimeStatus dco_decode_qwen_runtime_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return QwenRuntimeStatus(
      modelDir: dco_decode_String(arr[0]),
      decoderFile: dco_decode_String(arr[1]),
      encoderEp: dco_decode_String(arr[2]),
      decoderBackend: dco_decode_String(arr[3]),
      decoderOffload: dco_decode_String(arr[4]),
    );
  }

  @protected
  QwenWarmupConfig dco_decode_qwen_warmup_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return QwenWarmupConfig(
      asrModelDir: dco_decode_String(arr[0]),
      alignerModelDir: dco_decode_opt_String(arr[1]),
      encoderBackend: dco_decode_encoder_backend(arr[2]),
      decoderBackend: dco_decode_decoder_backend(arr[3]),
    );
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_String(arr[1]));
  }

  @protected
  (BigInt, BigInt) dco_decode_record_usize_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_usize(arr[0]), dco_decode_usize(arr[1]));
  }

  @protected
  TimestampMode dco_decode_timestamp_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TimestampMode.values[raw as int];
  }

  @protected
  TranscriptionEvent dco_decode_transcription_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return TranscriptionEvent_Progress(dco_decode_i_32(raw[1]));
      case 1:
        return TranscriptionEvent_ProgressDetail(
          processedMs: dco_decode_i_64(raw[1]),
          totalMs: dco_decode_i_64(raw[2]),
        );
      case 2:
        return TranscriptionEvent_Success(
          dco_decode_list_transcription_segment(raw[1]),
        );
      case 3:
        return TranscriptionEvent_Failure(dco_decode_String(raw[1]));
      case 4:
        return TranscriptionEvent_Segment(
          dco_decode_box_autoadd_transcription_segment(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  TranscriptionSegment dco_decode_transcription_segment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return TranscriptionSegment(
      startMs: dco_decode_i_64(arr[0]),
      endMs: dco_decode_i_64(arr[1]),
      text: dco_decode_String(arr[2]),
      words: dco_decode_list_word_item(arr[3]),
      timestampQuality: dco_decode_String(arr[4]),
    );
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  VulkanDeviceInfo dco_decode_vulkan_device_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return VulkanDeviceInfo(
      id: dco_decode_i_32(arr[0]),
      name: dco_decode_String(arr[1]),
      totalVramBytes: dco_decode_u_64(arr[2]),
    );
  }

  @protected
  WordItem dco_decode_word_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return WordItem(
      text: dco_decode_String(arr[0]),
      startMs: dco_decode_i_64(arr[1]),
      endMs: dco_decode_i_64(arr[2]),
      confidence: dco_decode_f_32(arr[3]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  SileroVadEngine
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSileroVadEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SileroVadEngineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SileroVadEngine
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSileroVadEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SileroVadEngineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SileroVadEngine
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSileroVadEngine(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SileroVadEngineImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<FfmpegEvent> sse_decode_StreamSink_ffmpeg_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<TranscriptionEvent>
  sse_decode_StreamSink_transcription_event_Sse(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AudioTrackInfo sse_decode_audio_track_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_index = sse_decode_usize(deserializer);
    var var_codecName = sse_decode_String(deserializer);
    var var_language = sse_decode_opt_String(deserializer);
    var var_title = sse_decode_opt_String(deserializer);
    return AudioTrackInfo(
      index: var_index,
      codecName: var_codecName,
      language: var_language,
      title: var_title,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  PipelineConfig sse_decode_box_autoadd_pipeline_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_pipeline_config(deserializer));
  }

  @protected
  QwenRuntimeStatus sse_decode_box_autoadd_qwen_runtime_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_qwen_runtime_status(deserializer));
  }

  @protected
  QwenWarmupConfig sse_decode_box_autoadd_qwen_warmup_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_qwen_warmup_config(deserializer));
  }

  @protected
  TranscriptionEvent sse_decode_box_autoadd_transcription_event(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_transcription_event(deserializer));
  }

  @protected
  TranscriptionSegment sse_decode_box_autoadd_transcription_segment(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_transcription_segment(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_usize(deserializer));
  }

  @protected
  ComputeDeviceInfo sse_decode_compute_device_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_vendor = sse_decode_String(deserializer);
    var var_vramMb = sse_decode_u_64(deserializer);
    var var_supportsVulkan = sse_decode_bool(deserializer);
    var var_supportsDirectml = sse_decode_bool(deserializer);
    return ComputeDeviceInfo(
      name: var_name,
      vendor: var_vendor,
      vramMb: var_vramMb,
      supportsVulkan: var_supportsVulkan,
      supportsDirectml: var_supportsDirectml,
    );
  }

  @protected
  DecoderBackend sse_decode_decoder_backend(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return DecoderBackend.values[inner];
  }

  @protected
  EncoderBackend sse_decode_encoder_backend(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return EncoderBackend.values[inner];
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FfmpegEvent sse_decode_ffmpeg_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_progress = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_success = sse_decode_opt_String(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return FfmpegEvent(
      progress: var_progress,
      success: var_success,
      error: var_error,
    );
  }

  @protected
  HardwareAccelerationInfo sse_decode_hardware_acceleration_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_isVulkanAvailable = sse_decode_bool(deserializer);
    var var_devices = sse_decode_list_vulkan_device_info(deserializer);
    return HardwareAccelerationInfo(
      isVulkanAvailable: var_isVulkanAvailable,
      devices: var_devices,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<AudioTrackInfo> sse_decode_list_audio_track_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AudioTrackInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_audio_track_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<ComputeDeviceInfo> sse_decode_list_compute_device_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ComputeDeviceInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_compute_device_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(BigInt, BigInt)> sse_decode_list_record_usize_usize(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(BigInt, BigInt)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_usize_usize(deserializer));
    }
    return ans_;
  }

  @protected
  List<TranscriptionSegment> sse_decode_list_transcription_segment(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TranscriptionSegment>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_transcription_segment(deserializer));
    }
    return ans_;
  }

  @protected
  List<VulkanDeviceInfo> sse_decode_list_vulkan_device_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <VulkanDeviceInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_vulkan_device_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<WordItem> sse_decode_list_word_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <WordItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_word_item(deserializer));
    }
    return ans_;
  }

  @protected
  ModelInfo sse_decode_model_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_modelId = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_valid = sse_decode_bool(deserializer);
    var var_totalSizeBytes = sse_decode_u_64(deserializer);
    var var_missingFiles = sse_decode_list_String(deserializer);
    return ModelInfo(
      modelId: var_modelId,
      path: var_path,
      valid: var_valid,
      totalSizeBytes: var_totalSizeBytes,
      missingFiles: var_missingFiles,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  QwenRuntimeStatus? sse_decode_opt_box_autoadd_qwen_runtime_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_qwen_runtime_status(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_usize(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PipelineConfig sse_decode_pipeline_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ffmpegPath = sse_decode_String(deserializer);
    var var_inputPath = sse_decode_String(deserializer);
    var var_modelPath = sse_decode_String(deserializer);
    var var_vadModelPath = sse_decode_String(deserializer);
    var var_dfModelPath = sse_decode_String(deserializer);
    var var_asrModelDir = sse_decode_String(deserializer);
    var var_alignerModelDir = sse_decode_opt_String(deserializer);
    var var_decoderFile = sse_decode_opt_String(deserializer);
    var var_contextPrompt = sse_decode_opt_String(deserializer);
    var var_encoderBackend = sse_decode_encoder_backend(deserializer);
    var var_decoderBackend = sse_decode_decoder_backend(deserializer);
    var var_timestampMode = sse_decode_timestamp_mode(deserializer);
    var var_language = sse_decode_opt_String(deserializer);
    var var_translate = sse_decode_bool(deserializer);
    var var_threads = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_useGpu = sse_decode_bool(deserializer);
    var var_toSimplified = sse_decode_bool(deserializer);
    var var_noContext = sse_decode_bool(deserializer);
    var var_noStateHistory = sse_decode_bool(deserializer);
    var var_enableDenoise = sse_decode_bool(deserializer);
    var var_vadEnabled = sse_decode_bool(deserializer);
    var var_vadThreshold = sse_decode_f_64(deserializer);
    var var_vadMinSpeechMs = sse_decode_i_32(deserializer);
    var var_vadMinSilenceMs = sse_decode_i_32(deserializer);
    var var_selectedAudioTrack = sse_decode_opt_box_autoadd_usize(deserializer);
    return PipelineConfig(
      ffmpegPath: var_ffmpegPath,
      inputPath: var_inputPath,
      modelPath: var_modelPath,
      vadModelPath: var_vadModelPath,
      dfModelPath: var_dfModelPath,
      asrModelDir: var_asrModelDir,
      alignerModelDir: var_alignerModelDir,
      decoderFile: var_decoderFile,
      contextPrompt: var_contextPrompt,
      encoderBackend: var_encoderBackend,
      decoderBackend: var_decoderBackend,
      timestampMode: var_timestampMode,
      language: var_language,
      translate: var_translate,
      threads: var_threads,
      useGpu: var_useGpu,
      toSimplified: var_toSimplified,
      noContext: var_noContext,
      noStateHistory: var_noStateHistory,
      enableDenoise: var_enableDenoise,
      vadEnabled: var_vadEnabled,
      vadThreshold: var_vadThreshold,
      vadMinSpeechMs: var_vadMinSpeechMs,
      vadMinSilenceMs: var_vadMinSilenceMs,
      selectedAudioTrack: var_selectedAudioTrack,
    );
  }

  @protected
  QwenHardwareInfo sse_decode_qwen_hardware_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_vulkanAvailable = sse_decode_bool(deserializer);
    var var_directmlAvailable = sse_decode_bool(deserializer);
    var var_cudaAvailable = sse_decode_bool(deserializer);
    var var_cpuAvailable = sse_decode_bool(deserializer);
    var var_devices = sse_decode_list_compute_device_info(deserializer);
    var var_recommendedEncoderBackend = sse_decode_encoder_backend(
      deserializer,
    );
    var var_recommendedDecoderBackend = sse_decode_decoder_backend(
      deserializer,
    );
    return QwenHardwareInfo(
      vulkanAvailable: var_vulkanAvailable,
      directmlAvailable: var_directmlAvailable,
      cudaAvailable: var_cudaAvailable,
      cpuAvailable: var_cpuAvailable,
      devices: var_devices,
      recommendedEncoderBackend: var_recommendedEncoderBackend,
      recommendedDecoderBackend: var_recommendedDecoderBackend,
    );
  }

  @protected
  QwenRuntimeStatus sse_decode_qwen_runtime_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_modelDir = sse_decode_String(deserializer);
    var var_decoderFile = sse_decode_String(deserializer);
    var var_encoderEp = sse_decode_String(deserializer);
    var var_decoderBackend = sse_decode_String(deserializer);
    var var_decoderOffload = sse_decode_String(deserializer);
    return QwenRuntimeStatus(
      modelDir: var_modelDir,
      decoderFile: var_decoderFile,
      encoderEp: var_encoderEp,
      decoderBackend: var_decoderBackend,
      decoderOffload: var_decoderOffload,
    );
  }

  @protected
  QwenWarmupConfig sse_decode_qwen_warmup_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_asrModelDir = sse_decode_String(deserializer);
    var var_alignerModelDir = sse_decode_opt_String(deserializer);
    var var_encoderBackend = sse_decode_encoder_backend(deserializer);
    var var_decoderBackend = sse_decode_decoder_backend(deserializer);
    return QwenWarmupConfig(
      asrModelDir: var_asrModelDir,
      alignerModelDir: var_alignerModelDir,
      encoderBackend: var_encoderBackend,
      decoderBackend: var_decoderBackend,
    );
  }

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  (BigInt, BigInt) sse_decode_record_usize_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_usize(deserializer);
    var var_field1 = sse_decode_usize(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  TimestampMode sse_decode_timestamp_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return TimestampMode.values[inner];
  }

  @protected
  TranscriptionEvent sse_decode_transcription_event(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_i_32(deserializer);
        return TranscriptionEvent_Progress(var_field0);
      case 1:
        var var_processedMs = sse_decode_i_64(deserializer);
        var var_totalMs = sse_decode_i_64(deserializer);
        return TranscriptionEvent_ProgressDetail(
          processedMs: var_processedMs,
          totalMs: var_totalMs,
        );
      case 2:
        var var_field0 = sse_decode_list_transcription_segment(deserializer);
        return TranscriptionEvent_Success(var_field0);
      case 3:
        var var_field0 = sse_decode_String(deserializer);
        return TranscriptionEvent_Failure(var_field0);
      case 4:
        var var_field0 = sse_decode_box_autoadd_transcription_segment(
          deserializer,
        );
        return TranscriptionEvent_Segment(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  TranscriptionSegment sse_decode_transcription_segment(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_startMs = sse_decode_i_64(deserializer);
    var var_endMs = sse_decode_i_64(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_words = sse_decode_list_word_item(deserializer);
    var var_timestampQuality = sse_decode_String(deserializer);
    return TranscriptionSegment(
      startMs: var_startMs,
      endMs: var_endMs,
      text: var_text,
      words: var_words,
      timestampQuality: var_timestampQuality,
    );
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  VulkanDeviceInfo sse_decode_vulkan_device_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_32(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_totalVramBytes = sse_decode_u_64(deserializer);
    return VulkanDeviceInfo(
      id: var_id,
      name: var_name,
      totalVramBytes: var_totalVramBytes,
    );
  }

  @protected
  WordItem sse_decode_word_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_text = sse_decode_String(deserializer);
    var var_startMs = sse_decode_i_64(deserializer);
    var var_endMs = sse_decode_i_64(deserializer);
    var var_confidence = sse_decode_f_32(deserializer);
    return WordItem(
      text: var_text,
      startMs: var_startMs,
      endMs: var_endMs,
      confidence: var_confidence,
    );
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSileroVadEngine(
    SileroVadEngine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SileroVadEngineImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSileroVadEngine(
    SileroVadEngine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SileroVadEngineImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSileroVadEngine(
    SileroVadEngine self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SileroVadEngineImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_ffmpeg_event_Sse(
    RustStreamSink<FfmpegEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffmpeg_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_transcription_event_Sse(
    RustStreamSink<TranscriptionEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_transcription_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_audio_track_info(
    AudioTrackInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self.index, serializer);
    sse_encode_String(self.codecName, serializer);
    sse_encode_opt_String(self.language, serializer);
    sse_encode_opt_String(self.title, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_pipeline_config(
    PipelineConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_pipeline_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_qwen_runtime_status(
    QwenRuntimeStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_qwen_runtime_status(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_qwen_warmup_config(
    QwenWarmupConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_qwen_warmup_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_transcription_event(
    TranscriptionEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_transcription_event(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_transcription_segment(
    TranscriptionSegment self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_transcription_segment(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self, serializer);
  }

  @protected
  void sse_encode_compute_device_info(
    ComputeDeviceInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.vendor, serializer);
    sse_encode_u_64(self.vramMb, serializer);
    sse_encode_bool(self.supportsVulkan, serializer);
    sse_encode_bool(self.supportsDirectml, serializer);
  }

  @protected
  void sse_encode_decoder_backend(
    DecoderBackend self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_encoder_backend(
    EncoderBackend self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_ffmpeg_event(FfmpegEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_i_32(self.progress, serializer);
    sse_encode_opt_String(self.success, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_hardware_acceleration_info(
    HardwareAccelerationInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.isVulkanAvailable, serializer);
    sse_encode_list_vulkan_device_info(self.devices, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_audio_track_info(
    List<AudioTrackInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_audio_track_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_compute_device_info(
    List<ComputeDeviceInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_compute_device_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_loose(
    List<double> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(
      self is Float32List ? self : Float32List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_usize_usize(
    List<(BigInt, BigInt)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_usize_usize(item, serializer);
    }
  }

  @protected
  void sse_encode_list_transcription_segment(
    List<TranscriptionSegment> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_transcription_segment(item, serializer);
    }
  }

  @protected
  void sse_encode_list_vulkan_device_info(
    List<VulkanDeviceInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_vulkan_device_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_word_item(
    List<WordItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_word_item(item, serializer);
    }
  }

  @protected
  void sse_encode_model_info(ModelInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.modelId, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_bool(self.valid, serializer);
    sse_encode_u_64(self.totalSizeBytes, serializer);
    sse_encode_list_String(self.missingFiles, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_qwen_runtime_status(
    QwenRuntimeStatus? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_qwen_runtime_status(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_usize(
    BigInt? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_usize(self, serializer);
    }
  }

  @protected
  void sse_encode_pipeline_config(
    PipelineConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.ffmpegPath, serializer);
    sse_encode_String(self.inputPath, serializer);
    sse_encode_String(self.modelPath, serializer);
    sse_encode_String(self.vadModelPath, serializer);
    sse_encode_String(self.dfModelPath, serializer);
    sse_encode_String(self.asrModelDir, serializer);
    sse_encode_opt_String(self.alignerModelDir, serializer);
    sse_encode_opt_String(self.decoderFile, serializer);
    sse_encode_opt_String(self.contextPrompt, serializer);
    sse_encode_encoder_backend(self.encoderBackend, serializer);
    sse_encode_decoder_backend(self.decoderBackend, serializer);
    sse_encode_timestamp_mode(self.timestampMode, serializer);
    sse_encode_opt_String(self.language, serializer);
    sse_encode_bool(self.translate, serializer);
    sse_encode_opt_box_autoadd_i_32(self.threads, serializer);
    sse_encode_bool(self.useGpu, serializer);
    sse_encode_bool(self.toSimplified, serializer);
    sse_encode_bool(self.noContext, serializer);
    sse_encode_bool(self.noStateHistory, serializer);
    sse_encode_bool(self.enableDenoise, serializer);
    sse_encode_bool(self.vadEnabled, serializer);
    sse_encode_f_64(self.vadThreshold, serializer);
    sse_encode_i_32(self.vadMinSpeechMs, serializer);
    sse_encode_i_32(self.vadMinSilenceMs, serializer);
    sse_encode_opt_box_autoadd_usize(self.selectedAudioTrack, serializer);
  }

  @protected
  void sse_encode_qwen_hardware_info(
    QwenHardwareInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.vulkanAvailable, serializer);
    sse_encode_bool(self.directmlAvailable, serializer);
    sse_encode_bool(self.cudaAvailable, serializer);
    sse_encode_bool(self.cpuAvailable, serializer);
    sse_encode_list_compute_device_info(self.devices, serializer);
    sse_encode_encoder_backend(self.recommendedEncoderBackend, serializer);
    sse_encode_decoder_backend(self.recommendedDecoderBackend, serializer);
  }

  @protected
  void sse_encode_qwen_runtime_status(
    QwenRuntimeStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.modelDir, serializer);
    sse_encode_String(self.decoderFile, serializer);
    sse_encode_String(self.encoderEp, serializer);
    sse_encode_String(self.decoderBackend, serializer);
    sse_encode_String(self.decoderOffload, serializer);
  }

  @protected
  void sse_encode_qwen_warmup_config(
    QwenWarmupConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.asrModelDir, serializer);
    sse_encode_opt_String(self.alignerModelDir, serializer);
    sse_encode_encoder_backend(self.encoderBackend, serializer);
    sse_encode_decoder_backend(self.decoderBackend, serializer);
  }

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_record_usize_usize(
    (BigInt, BigInt) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self.$1, serializer);
    sse_encode_usize(self.$2, serializer);
  }

  @protected
  void sse_encode_timestamp_mode(TimestampMode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_transcription_event(
    TranscriptionEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case TranscriptionEvent_Progress(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_i_32(field0, serializer);
      case TranscriptionEvent_ProgressDetail(
        processedMs: final processedMs,
        totalMs: final totalMs,
      ):
        sse_encode_i_32(1, serializer);
        sse_encode_i_64(processedMs, serializer);
        sse_encode_i_64(totalMs, serializer);
      case TranscriptionEvent_Success(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_list_transcription_segment(field0, serializer);
      case TranscriptionEvent_Failure(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_String(field0, serializer);
      case TranscriptionEvent_Segment(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_box_autoadd_transcription_segment(field0, serializer);
    }
  }

  @protected
  void sse_encode_transcription_segment(
    TranscriptionSegment self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.startMs, serializer);
    sse_encode_i_64(self.endMs, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_list_word_item(self.words, serializer);
    sse_encode_String(self.timestampQuality, serializer);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_vulkan_device_info(
    VulkanDeviceInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_u_64(self.totalVramBytes, serializer);
  }

  @protected
  void sse_encode_word_item(WordItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.text, serializer);
    sse_encode_i_64(self.startMs, serializer);
    sse_encode_i_64(self.endMs, serializer);
    sse_encode_f_32(self.confidence, serializer);
  }
}

@sealed
class SileroVadEngineImpl extends RustOpaque implements SileroVadEngine {
  // Not to be used by end users
  SileroVadEngineImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  SileroVadEngineImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_SileroVadEngine,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_SileroVadEngine,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_SileroVadEnginePtr,
  );

  Future<List<(BigInt, BigInt)>> detectSpeechSegments({
    required List<double> samples,
    required int minSpeechMs,
    required int minSilenceMs,
    required double threshold,
  }) =>
      RustLib.instance.api.crateApiSileroVadSileroVadEngineDetectSpeechSegments(
        that: this,
        samples: samples,
        minSpeechMs: minSpeechMs,
        minSilenceMs: minSilenceMs,
        threshold: threshold,
      );
}
