// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/ffmpeg.dart';
import 'api/hardware.dart';
import 'api/models.dart';
import 'api/qwen.dart';
import 'api/simple.dart';
import 'api/stream_pipeline.dart';
import 'api/whisper.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'qwen/backend.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<FfmpegEvent> dco_decode_StreamSink_ffmpeg_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<TranscriptionEvent>
  dco_decode_StreamSink_transcription_event_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  TranscriptionSink dco_decode_TraitDef_TranscriptionSink(dynamic raw);

  @protected
  AudioTrackInfo dco_decode_audio_track_info(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PipelineConfig dco_decode_box_autoadd_pipeline_config(dynamic raw);

  @protected
  QwenWarmupConfig dco_decode_box_autoadd_qwen_warmup_config(dynamic raw);

  @protected
  TranscriptionEvent dco_decode_box_autoadd_transcription_event(dynamic raw);

  @protected
  TranscriptionSegment dco_decode_box_autoadd_transcription_segment(
    dynamic raw,
  );

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw);

  @protected
  ComputeDeviceInfo dco_decode_compute_device_info(dynamic raw);

  @protected
  DecoderBackend dco_decode_decoder_backend(dynamic raw);

  @protected
  EncoderBackend dco_decode_encoder_backend(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FfmpegEvent dco_decode_ffmpeg_event(dynamic raw);

  @protected
  HardwareAccelerationInfo dco_decode_hardware_acceleration_info(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AudioTrackInfo> dco_decode_list_audio_track_info(dynamic raw);

  @protected
  List<ComputeDeviceInfo> dco_decode_list_compute_device_info(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<TranscriptionSegment> dco_decode_list_transcription_segment(dynamic raw);

  @protected
  List<VulkanDeviceInfo> dco_decode_list_vulkan_device_info(dynamic raw);

  @protected
  List<WordItem> dco_decode_list_word_item(dynamic raw);

  @protected
  ModelInfo dco_decode_model_info(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw);

  @protected
  PipelineConfig dco_decode_pipeline_config(dynamic raw);

  @protected
  QwenHardwareInfo dco_decode_qwen_hardware_info(dynamic raw);

  @protected
  QwenWarmupConfig dco_decode_qwen_warmup_config(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  TimestampMode dco_decode_timestamp_mode(dynamic raw);

  @protected
  TranscriptionEvent dco_decode_transcription_event(dynamic raw);

  @protected
  TranscriptionSegment dco_decode_transcription_segment(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  VulkanDeviceInfo dco_decode_vulkan_device_info(dynamic raw);

  @protected
  WordItem dco_decode_word_item(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<FfmpegEvent> sse_decode_StreamSink_ffmpeg_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<TranscriptionEvent>
  sse_decode_StreamSink_transcription_event_Sse(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AudioTrackInfo sse_decode_audio_track_info(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PipelineConfig sse_decode_box_autoadd_pipeline_config(
    SseDeserializer deserializer,
  );

  @protected
  QwenWarmupConfig sse_decode_box_autoadd_qwen_warmup_config(
    SseDeserializer deserializer,
  );

  @protected
  TranscriptionEvent sse_decode_box_autoadd_transcription_event(
    SseDeserializer deserializer,
  );

  @protected
  TranscriptionSegment sse_decode_box_autoadd_transcription_segment(
    SseDeserializer deserializer,
  );

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  ComputeDeviceInfo sse_decode_compute_device_info(
    SseDeserializer deserializer,
  );

  @protected
  DecoderBackend sse_decode_decoder_backend(SseDeserializer deserializer);

  @protected
  EncoderBackend sse_decode_encoder_backend(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FfmpegEvent sse_decode_ffmpeg_event(SseDeserializer deserializer);

  @protected
  HardwareAccelerationInfo sse_decode_hardware_acceleration_info(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AudioTrackInfo> sse_decode_list_audio_track_info(
    SseDeserializer deserializer,
  );

  @protected
  List<ComputeDeviceInfo> sse_decode_list_compute_device_info(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<TranscriptionSegment> sse_decode_list_transcription_segment(
    SseDeserializer deserializer,
  );

  @protected
  List<VulkanDeviceInfo> sse_decode_list_vulkan_device_info(
    SseDeserializer deserializer,
  );

  @protected
  List<WordItem> sse_decode_list_word_item(SseDeserializer deserializer);

  @protected
  ModelInfo sse_decode_model_info(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  PipelineConfig sse_decode_pipeline_config(SseDeserializer deserializer);

  @protected
  QwenHardwareInfo sse_decode_qwen_hardware_info(SseDeserializer deserializer);

  @protected
  QwenWarmupConfig sse_decode_qwen_warmup_config(SseDeserializer deserializer);

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  TimestampMode sse_decode_timestamp_mode(SseDeserializer deserializer);

  @protected
  TranscriptionEvent sse_decode_transcription_event(
    SseDeserializer deserializer,
  );

  @protected
  TranscriptionSegment sse_decode_transcription_segment(
    SseDeserializer deserializer,
  );

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  VulkanDeviceInfo sse_decode_vulkan_device_info(SseDeserializer deserializer);

  @protected
  WordItem sse_decode_word_item(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_ffmpeg_event_Sse(
    RustStreamSink<FfmpegEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_transcription_event_Sse(
    RustStreamSink<TranscriptionEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_audio_track_info(
    AudioTrackInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_pipeline_config(
    PipelineConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_qwen_warmup_config(
    QwenWarmupConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_transcription_event(
    TranscriptionEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_transcription_segment(
    TranscriptionSegment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_compute_device_info(
    ComputeDeviceInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_decoder_backend(
    DecoderBackend self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_encoder_backend(
    EncoderBackend self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_ffmpeg_event(FfmpegEvent self, SseSerializer serializer);

  @protected
  void sse_encode_hardware_acceleration_info(
    HardwareAccelerationInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_audio_track_info(
    List<AudioTrackInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_compute_device_info(
    List<ComputeDeviceInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_transcription_segment(
    List<TranscriptionSegment> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_vulkan_device_info(
    List<VulkanDeviceInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_word_item(List<WordItem> self, SseSerializer serializer);

  @protected
  void sse_encode_model_info(ModelInfo self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_usize(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_pipeline_config(
    PipelineConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qwen_hardware_info(
    QwenHardwareInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_qwen_warmup_config(
    QwenWarmupConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_timestamp_mode(TimestampMode self, SseSerializer serializer);

  @protected
  void sse_encode_transcription_event(
    TranscriptionEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transcription_segment(
    TranscriptionSegment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_vulkan_device_info(
    VulkanDeviceInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_word_item(WordItem self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
