// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/ffmpeg.dart';
import 'api/simple.dart';
import 'api/stream_pipeline.dart';
import 'api/whisper.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<FfmpegEvent> dco_decode_StreamSink_ffmpeg_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<TranscriptionEvent>
  dco_decode_StreamSink_transcription_event_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  TranscriptionSegment dco_decode_box_autoadd_transcription_segment(
    dynamic raw,
  );

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FfmpegEvent dco_decode_ffmpeg_event(dynamic raw);

  @protected
  HardwareAccelerationInfo dco_decode_hardware_acceleration_info(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<TranscriptionSegment> dco_decode_list_transcription_segment(dynamic raw);

  @protected
  List<VulkanDeviceInfo> dco_decode_list_vulkan_device_info(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  TranscriptionEvent dco_decode_transcription_event(dynamic raw);

  @protected
  TranscriptionSegment dco_decode_transcription_segment(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VulkanDeviceInfo dco_decode_vulkan_device_info(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<FfmpegEvent> sse_decode_StreamSink_ffmpeg_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<TranscriptionEvent>
  sse_decode_StreamSink_transcription_event_Sse(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  TranscriptionSegment sse_decode_box_autoadd_transcription_segment(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FfmpegEvent sse_decode_ffmpeg_event(SseDeserializer deserializer);

  @protected
  HardwareAccelerationInfo sse_decode_hardware_acceleration_info(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<TranscriptionSegment> sse_decode_list_transcription_segment(
    SseDeserializer deserializer,
  );

  @protected
  List<VulkanDeviceInfo> sse_decode_list_vulkan_device_info(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  TranscriptionEvent sse_decode_transcription_event(
    SseDeserializer deserializer,
  );

  @protected
  TranscriptionSegment sse_decode_transcription_segment(
    SseDeserializer deserializer,
  );

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VulkanDeviceInfo sse_decode_vulkan_device_info(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_ffmpeg_event_Sse(
    RustStreamSink<FfmpegEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_transcription_event_Sse(
    RustStreamSink<TranscriptionEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_transcription_segment(
    TranscriptionSegment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_ffmpeg_event(FfmpegEvent self, SseSerializer serializer);

  @protected
  void sse_encode_hardware_acceleration_info(
    HardwareAccelerationInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_transcription_segment(
    List<TranscriptionSegment> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_vulkan_device_info(
    List<VulkanDeviceInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_transcription_event(
    TranscriptionEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transcription_segment(
    TranscriptionSegment self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_vulkan_device_info(
    VulkanDeviceInfo self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
