// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/ffmpeg.dart';
import 'api/simple.dart';
import 'api/stream_pipeline.dart';
import 'api/whisper.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1618686293;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_audio2srt',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiWhisperConvertChinese({
    required String text,
    required bool toSimplified,
  });

  Future<List<String>> crateApiWhisperConvertChineseList({
    required List<String> texts,
    required bool toSimplified,
  });

  Stream<FfmpegEvent> crateApiFfmpegExtractAudioFromMedia({
    required String ffmpegPath,
    required String inputPath,
    required String outputPath,
  });

  Future<HardwareAccelerationInfo> crateApiWhisperGetHardwareAccelerationInfo();

  String crateApiSimpleGreet({required String name});

  Future<HardwareAccelerationInfo>
  crateApiWhisperHardwareAccelerationInfoDefault();

  Future<void> crateApiSimpleInitApp();

  Stream<FfmpegEvent> crateApiFfmpegMuxSrtToVideo({
    required String ffmpegPath,
    required String videoPath,
    required String srtPath,
    required String outputPath,
    required bool hardBurn,
  });

  Stream<TranscriptionEvent> crateApiWhisperTranscribe({
    required String modelPath,
    required String vadModelPath,
    required String audioPath,
    String? language,
    required bool translate,
    int? threads,
    required bool useGpu,
    required bool vadEnabled,
    required double vadThreshold,
    required int vadMinSpeechMs,
    required int vadMinSilenceMs,
    required double temperature,
    required double temperatureInc,
    required double entropyThold,
    required double logprobThold,
    required double noSpeechThold,
    required bool noContext,
  });

  Stream<TranscriptionEvent> crateApiStreamPipelineTranscribeStream({
    required String ffmpegPath,
    required String inputPath,
    required String modelPath,
    required String vadModelPath,
    required String dfModelPath,
    String? language,
    required bool translate,
    int? threads,
    required bool useGpu,
    required bool toSimplified,
    required bool enableDenoise,
    required bool vadEnabled,
    required double vadThreshold,
    required int vadMinSpeechMs,
    required int vadMinSilenceMs,
    required bool noContext,
  });

  Future<TranscriptionSegment> crateApiWhisperTranscriptionSegmentDefault();

  Future<VulkanDeviceInfo> crateApiWhisperVulkanDeviceInfoDefault();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiWhisperConvertChinese({
    required String text,
    required bool toSimplified,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          sse_encode_bool(toSimplified, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWhisperConvertChineseConstMeta,
        argValues: [text, toSimplified],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperConvertChineseConstMeta =>
      const TaskConstMeta(
        debugName: "convert_chinese",
        argNames: ["text", "toSimplified"],
      );

  @override
  Future<List<String>> crateApiWhisperConvertChineseList({
    required List<String> texts,
    required bool toSimplified,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(texts, serializer);
          sse_encode_bool(toSimplified, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWhisperConvertChineseListConstMeta,
        argValues: [texts, toSimplified],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperConvertChineseListConstMeta =>
      const TaskConstMeta(
        debugName: "convert_chinese_list",
        argNames: ["texts", "toSimplified"],
      );

  @override
  Stream<FfmpegEvent> crateApiFfmpegExtractAudioFromMedia({
    required String ffmpegPath,
    required String inputPath,
    required String outputPath,
  }) {
    final sink = RustStreamSink<FfmpegEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_ffmpeg_event_Sse(sink, serializer);
            sse_encode_String(ffmpegPath, serializer);
            sse_encode_String(inputPath, serializer);
            sse_encode_String(outputPath, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 3,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiFfmpegExtractAudioFromMediaConstMeta,
          argValues: [sink, ffmpegPath, inputPath, outputPath],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiFfmpegExtractAudioFromMediaConstMeta =>
      const TaskConstMeta(
        debugName: "extract_audio_from_media",
        argNames: ["sink", "ffmpegPath", "inputPath", "outputPath"],
      );

  @override
  Future<HardwareAccelerationInfo>
  crateApiWhisperGetHardwareAccelerationInfo() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_hardware_acceleration_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWhisperGetHardwareAccelerationInfoConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperGetHardwareAccelerationInfoConstMeta =>
      const TaskConstMeta(
        debugName: "get_hardware_acceleration_info",
        argNames: [],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<HardwareAccelerationInfo>
  crateApiWhisperHardwareAccelerationInfoDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_hardware_acceleration_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWhisperHardwareAccelerationInfoDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperHardwareAccelerationInfoDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "hardware_acceleration_info_default",
        argNames: [],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Stream<FfmpegEvent> crateApiFfmpegMuxSrtToVideo({
    required String ffmpegPath,
    required String videoPath,
    required String srtPath,
    required String outputPath,
    required bool hardBurn,
  }) {
    final sink = RustStreamSink<FfmpegEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_ffmpeg_event_Sse(sink, serializer);
            sse_encode_String(ffmpegPath, serializer);
            sse_encode_String(videoPath, serializer);
            sse_encode_String(srtPath, serializer);
            sse_encode_String(outputPath, serializer);
            sse_encode_bool(hardBurn, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 8,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiFfmpegMuxSrtToVideoConstMeta,
          argValues: [
            sink,
            ffmpegPath,
            videoPath,
            srtPath,
            outputPath,
            hardBurn,
          ],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiFfmpegMuxSrtToVideoConstMeta =>
      const TaskConstMeta(
        debugName: "mux_srt_to_video",
        argNames: [
          "sink",
          "ffmpegPath",
          "videoPath",
          "srtPath",
          "outputPath",
          "hardBurn",
        ],
      );

  @override
  Stream<TranscriptionEvent> crateApiWhisperTranscribe({
    required String modelPath,
    required String vadModelPath,
    required String audioPath,
    String? language,
    required bool translate,
    int? threads,
    required bool useGpu,
    required bool vadEnabled,
    required double vadThreshold,
    required int vadMinSpeechMs,
    required int vadMinSilenceMs,
    required double temperature,
    required double temperatureInc,
    required double entropyThold,
    required double logprobThold,
    required double noSpeechThold,
    required bool noContext,
  }) {
    final sink = RustStreamSink<TranscriptionEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_transcription_event_Sse(sink, serializer);
            sse_encode_String(modelPath, serializer);
            sse_encode_String(vadModelPath, serializer);
            sse_encode_String(audioPath, serializer);
            sse_encode_opt_String(language, serializer);
            sse_encode_bool(translate, serializer);
            sse_encode_opt_box_autoadd_i_32(threads, serializer);
            sse_encode_bool(useGpu, serializer);
            sse_encode_bool(vadEnabled, serializer);
            sse_encode_f_32(vadThreshold, serializer);
            sse_encode_i_32(vadMinSpeechMs, serializer);
            sse_encode_i_32(vadMinSilenceMs, serializer);
            sse_encode_f_32(temperature, serializer);
            sse_encode_f_32(temperatureInc, serializer);
            sse_encode_f_32(entropyThold, serializer);
            sse_encode_f_32(logprobThold, serializer);
            sse_encode_f_32(noSpeechThold, serializer);
            sse_encode_bool(noContext, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 9,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiWhisperTranscribeConstMeta,
          argValues: [
            sink,
            modelPath,
            vadModelPath,
            audioPath,
            language,
            translate,
            threads,
            useGpu,
            vadEnabled,
            vadThreshold,
            vadMinSpeechMs,
            vadMinSilenceMs,
            temperature,
            temperatureInc,
            entropyThold,
            logprobThold,
            noSpeechThold,
            noContext,
          ],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiWhisperTranscribeConstMeta => const TaskConstMeta(
    debugName: "transcribe",
    argNames: [
      "sink",
      "modelPath",
      "vadModelPath",
      "audioPath",
      "language",
      "translate",
      "threads",
      "useGpu",
      "vadEnabled",
      "vadThreshold",
      "vadMinSpeechMs",
      "vadMinSilenceMs",
      "temperature",
      "temperatureInc",
      "entropyThold",
      "logprobThold",
      "noSpeechThold",
      "noContext",
    ],
  );

  @override
  Stream<TranscriptionEvent> crateApiStreamPipelineTranscribeStream({
    required String ffmpegPath,
    required String inputPath,
    required String modelPath,
    required String vadModelPath,
    required String dfModelPath,
    String? language,
    required bool translate,
    int? threads,
    required bool useGpu,
    required bool toSimplified,
    required bool enableDenoise,
    required bool vadEnabled,
    required double vadThreshold,
    required int vadMinSpeechMs,
    required int vadMinSilenceMs,
    required bool noContext,
  }) {
    final sink = RustStreamSink<TranscriptionEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_transcription_event_Sse(sink, serializer);
            sse_encode_String(ffmpegPath, serializer);
            sse_encode_String(inputPath, serializer);
            sse_encode_String(modelPath, serializer);
            sse_encode_String(vadModelPath, serializer);
            sse_encode_String(dfModelPath, serializer);
            sse_encode_opt_String(language, serializer);
            sse_encode_bool(translate, serializer);
            sse_encode_opt_box_autoadd_i_32(threads, serializer);
            sse_encode_bool(useGpu, serializer);
            sse_encode_bool(toSimplified, serializer);
            sse_encode_bool(enableDenoise, serializer);
            sse_encode_bool(vadEnabled, serializer);
            sse_encode_f_64(vadThreshold, serializer);
            sse_encode_i_32(vadMinSpeechMs, serializer);
            sse_encode_i_32(vadMinSilenceMs, serializer);
            sse_encode_bool(noContext, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 10,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiStreamPipelineTranscribeStreamConstMeta,
          argValues: [
            sink,
            ffmpegPath,
            inputPath,
            modelPath,
            vadModelPath,
            dfModelPath,
            language,
            translate,
            threads,
            useGpu,
            toSimplified,
            enableDenoise,
            vadEnabled,
            vadThreshold,
            vadMinSpeechMs,
            vadMinSilenceMs,
            noContext,
          ],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiStreamPipelineTranscribeStreamConstMeta =>
      const TaskConstMeta(
        debugName: "transcribe_stream",
        argNames: [
          "sink",
          "ffmpegPath",
          "inputPath",
          "modelPath",
          "vadModelPath",
          "dfModelPath",
          "language",
          "translate",
          "threads",
          "useGpu",
          "toSimplified",
          "enableDenoise",
          "vadEnabled",
          "vadThreshold",
          "vadMinSpeechMs",
          "vadMinSilenceMs",
          "noContext",
        ],
      );

  @override
  Future<TranscriptionSegment> crateApiWhisperTranscriptionSegmentDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_transcription_segment,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWhisperTranscriptionSegmentDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperTranscriptionSegmentDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "transcription_segment_default",
        argNames: [],
      );

  @override
  Future<VulkanDeviceInfo> crateApiWhisperVulkanDeviceInfoDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_vulkan_device_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWhisperVulkanDeviceInfoDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWhisperVulkanDeviceInfoDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "vulkan_device_info_default",
        argNames: [],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<FfmpegEvent> dco_decode_StreamSink_ffmpeg_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<TranscriptionEvent>
  dco_decode_StreamSink_transcription_event_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  TranscriptionSegment dco_decode_box_autoadd_transcription_segment(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_transcription_segment(raw);
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FfmpegEvent dco_decode_ffmpeg_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FfmpegEvent(
      progress: dco_decode_opt_box_autoadd_i_32(arr[0]),
      success: dco_decode_opt_String(arr[1]),
      error: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  HardwareAccelerationInfo dco_decode_hardware_acceleration_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return HardwareAccelerationInfo(
      isVulkanAvailable: dco_decode_bool(arr[0]),
      devices: dco_decode_list_vulkan_device_info(arr[1]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TranscriptionSegment> dco_decode_list_transcription_segment(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_transcription_segment)
        .toList();
  }

  @protected
  List<VulkanDeviceInfo> dco_decode_list_vulkan_device_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_vulkan_device_info).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  TranscriptionEvent dco_decode_transcription_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return TranscriptionEvent_Progress(dco_decode_i_32(raw[1]));
      case 1:
        return TranscriptionEvent_ProgressDetail(
          processedMs: dco_decode_i_64(raw[1]),
          totalMs: dco_decode_i_64(raw[2]),
        );
      case 2:
        return TranscriptionEvent_Success(
          dco_decode_list_transcription_segment(raw[1]),
        );
      case 3:
        return TranscriptionEvent_Failure(dco_decode_String(raw[1]));
      case 4:
        return TranscriptionEvent_Segment(
          dco_decode_box_autoadd_transcription_segment(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  TranscriptionSegment dco_decode_transcription_segment(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TranscriptionSegment(
      startMs: dco_decode_i_64(arr[0]),
      endMs: dco_decode_i_64(arr[1]),
      text: dco_decode_String(arr[2]),
    );
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VulkanDeviceInfo dco_decode_vulkan_device_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return VulkanDeviceInfo(
      id: dco_decode_i_32(arr[0]),
      name: dco_decode_String(arr[1]),
      totalVramBytes: dco_decode_u_64(arr[2]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<FfmpegEvent> sse_decode_StreamSink_ffmpeg_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<TranscriptionEvent>
  sse_decode_StreamSink_transcription_event_Sse(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  TranscriptionSegment sse_decode_box_autoadd_transcription_segment(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_transcription_segment(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FfmpegEvent sse_decode_ffmpeg_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_progress = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_success = sse_decode_opt_String(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return FfmpegEvent(
      progress: var_progress,
      success: var_success,
      error: var_error,
    );
  }

  @protected
  HardwareAccelerationInfo sse_decode_hardware_acceleration_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_isVulkanAvailable = sse_decode_bool(deserializer);
    var var_devices = sse_decode_list_vulkan_device_info(deserializer);
    return HardwareAccelerationInfo(
      isVulkanAvailable: var_isVulkanAvailable,
      devices: var_devices,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TranscriptionSegment> sse_decode_list_transcription_segment(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TranscriptionSegment>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_transcription_segment(deserializer));
    }
    return ans_;
  }

  @protected
  List<VulkanDeviceInfo> sse_decode_list_vulkan_device_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <VulkanDeviceInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_vulkan_device_info(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  TranscriptionEvent sse_decode_transcription_event(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_i_32(deserializer);
        return TranscriptionEvent_Progress(var_field0);
      case 1:
        var var_processedMs = sse_decode_i_64(deserializer);
        var var_totalMs = sse_decode_i_64(deserializer);
        return TranscriptionEvent_ProgressDetail(
          processedMs: var_processedMs,
          totalMs: var_totalMs,
        );
      case 2:
        var var_field0 = sse_decode_list_transcription_segment(deserializer);
        return TranscriptionEvent_Success(var_field0);
      case 3:
        var var_field0 = sse_decode_String(deserializer);
        return TranscriptionEvent_Failure(var_field0);
      case 4:
        var var_field0 = sse_decode_box_autoadd_transcription_segment(
          deserializer,
        );
        return TranscriptionEvent_Segment(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  TranscriptionSegment sse_decode_transcription_segment(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_startMs = sse_decode_i_64(deserializer);
    var var_endMs = sse_decode_i_64(deserializer);
    var var_text = sse_decode_String(deserializer);
    return TranscriptionSegment(
      startMs: var_startMs,
      endMs: var_endMs,
      text: var_text,
    );
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VulkanDeviceInfo sse_decode_vulkan_device_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_32(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_totalVramBytes = sse_decode_u_64(deserializer);
    return VulkanDeviceInfo(
      id: var_id,
      name: var_name,
      totalVramBytes: var_totalVramBytes,
    );
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_ffmpeg_event_Sse(
    RustStreamSink<FfmpegEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_ffmpeg_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_transcription_event_Sse(
    RustStreamSink<TranscriptionEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_transcription_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_transcription_segment(
    TranscriptionSegment self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_transcription_segment(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_ffmpeg_event(FfmpegEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_i_32(self.progress, serializer);
    sse_encode_opt_String(self.success, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_hardware_acceleration_info(
    HardwareAccelerationInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.isVulkanAvailable, serializer);
    sse_encode_list_vulkan_device_info(self.devices, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_transcription_segment(
    List<TranscriptionSegment> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_transcription_segment(item, serializer);
    }
  }

  @protected
  void sse_encode_list_vulkan_device_info(
    List<VulkanDeviceInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_vulkan_device_info(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_transcription_event(
    TranscriptionEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case TranscriptionEvent_Progress(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_i_32(field0, serializer);
      case TranscriptionEvent_ProgressDetail(
        processedMs: final processedMs,
        totalMs: final totalMs,
      ):
        sse_encode_i_32(1, serializer);
        sse_encode_i_64(processedMs, serializer);
        sse_encode_i_64(totalMs, serializer);
      case TranscriptionEvent_Success(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_list_transcription_segment(field0, serializer);
      case TranscriptionEvent_Failure(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_String(field0, serializer);
      case TranscriptionEvent_Segment(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_box_autoadd_transcription_segment(field0, serializer);
    }
  }

  @protected
  void sse_encode_transcription_segment(
    TranscriptionSegment self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.startMs, serializer);
    sse_encode_i_64(self.endMs, serializer);
    sse_encode_String(self.text, serializer);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_vulkan_device_info(
    VulkanDeviceInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_u_64(self.totalVramBytes, serializer);
  }
}
