// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ComputeDeviceInfo {
  final String name;
  final String vendor;
  final BigInt vramMb;
  final bool supportsVulkan;
  final bool supportsDirectml;

  const ComputeDeviceInfo({
    required this.name,
    required this.vendor,
    required this.vramMb,
    required this.supportsVulkan,
    required this.supportsDirectml,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      vendor.hashCode ^
      vramMb.hashCode ^
      supportsVulkan.hashCode ^
      supportsDirectml.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ComputeDeviceInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          vendor == other.vendor &&
          vramMb == other.vramMb &&
          supportsVulkan == other.supportsVulkan &&
          supportsDirectml == other.supportsDirectml;
}

enum DecoderBackend { auto, vulkan, cuda, cpu }

enum EncoderBackend { auto, directMl, cpu }

class QwenHardwareInfo {
  final bool vulkanAvailable;
  final bool directmlAvailable;
  final bool cudaAvailable;
  final bool cpuAvailable;
  final List<ComputeDeviceInfo> devices;
  final EncoderBackend recommendedEncoderBackend;
  final DecoderBackend recommendedDecoderBackend;

  const QwenHardwareInfo({
    required this.vulkanAvailable,
    required this.directmlAvailable,
    required this.cudaAvailable,
    required this.cpuAvailable,
    required this.devices,
    required this.recommendedEncoderBackend,
    required this.recommendedDecoderBackend,
  });

  @override
  int get hashCode =>
      vulkanAvailable.hashCode ^
      directmlAvailable.hashCode ^
      cudaAvailable.hashCode ^
      cpuAvailable.hashCode ^
      devices.hashCode ^
      recommendedEncoderBackend.hashCode ^
      recommendedDecoderBackend.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QwenHardwareInfo &&
          runtimeType == other.runtimeType &&
          vulkanAvailable == other.vulkanAvailable &&
          directmlAvailable == other.directmlAvailable &&
          cudaAvailable == other.cudaAvailable &&
          cpuAvailable == other.cpuAvailable &&
          devices == other.devices &&
          recommendedEncoderBackend == other.recommendedEncoderBackend &&
          recommendedDecoderBackend == other.recommendedDecoderBackend;
}
