[build]
jobs = 8

[env]
# 强制 CMake 使用 Ninja 构建，不受 MAX_PATH 限制
CMAKE_GENERATOR = "Ninja"

[target.x86_64-pc-windows-msvc]
rustflags = [
  "-C", "target-cpu=x86-64-v3",
  "-C", "link-arg=/DEBUG:NONE",
  "-C", "link-arg=/OPT:REF",
  "-C", "link-arg=/OPT:ICF",
]