[package]
name = "rust_lib_audio2srt"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.11.1"
whisper-rs = { version = "0.16.0" }
hound = "3.5.1"
anyhow = "1.0"
zhconv = "0.4.1"
rubato = "0.15"
deep_filter = { git = "https://github.com/Rikorose/DeepFilterNet", package = "deep_filter", features = ["tract"] }
deepfilter-rt = { git = "https://github.com/shimondoodkin/deepfilter-rt" }
ort = { version = "=2.0.0-rc.11", features = ["ndarray"] }
flate2 = "1.0"
tar = "0.4"
tract-core = "=0.21.4"
tract-onnx = "=0.21.4"


[features]
default = ["vulkan"]
vulkan = ["whisper-rs/vulkan"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }

[profile.dev]
debug-assertions = false

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"

