// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'common.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

Future<String> convertChinese({
  required String text,
  required bool toSimplified,
}) => RustLib.instance.api.crateApiCommonConvertChinese(
  text: text,
  toSimplified: toSimplified,
);

Future<List<String>> convertChineseList({
  required List<String> texts,
  required bool toSimplified,
}) => RustLib.instance.api.crateApiCommonConvertChineseList(
  texts: texts,
  toSimplified: toSimplified,
);

Future<void> registerThreadAsProAudio() =>
    RustLib.instance.api.crateApiCommonRegisterThreadAsProAudio();

@freezed
sealed class TranscriptionEvent with _$TranscriptionEvent {
  const TranscriptionEvent._();

  const factory TranscriptionEvent.progress(int field0) =
      TranscriptionEvent_Progress;
  const factory TranscriptionEvent.progressDetail({
    required PlatformInt64 processedMs,
    required PlatformInt64 totalMs,
  }) = TranscriptionEvent_ProgressDetail;
  const factory TranscriptionEvent.success(List<TranscriptionSegment> field0) =
      TranscriptionEvent_Success;
  const factory TranscriptionEvent.failure(String field0) =
      TranscriptionEvent_Failure;
  const factory TranscriptionEvent.segment(TranscriptionSegment field0) =
      TranscriptionEvent_Segment;
}

class TranscriptionSegment {
  final PlatformInt64 startMs;
  final PlatformInt64 endMs;
  final String text;
  final List<WordItem> words;
  final String timestampQuality;

  const TranscriptionSegment({
    required this.startMs,
    required this.endMs,
    required this.text,
    required this.words,
    required this.timestampQuality,
  });

  static Future<TranscriptionSegment> default_() =>
      RustLib.instance.api.crateApiCommonTranscriptionSegmentDefault();

  @override
  int get hashCode =>
      startMs.hashCode ^
      endMs.hashCode ^
      text.hashCode ^
      words.hashCode ^
      timestampQuality.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TranscriptionSegment &&
          runtimeType == other.runtimeType &&
          startMs == other.startMs &&
          endMs == other.endMs &&
          text == other.text &&
          words == other.words &&
          timestampQuality == other.timestampQuality;
}

class WordItem {
  final String text;
  final PlatformInt64 startMs;
  final PlatformInt64 endMs;
  final double confidence;

  const WordItem({
    required this.text,
    required this.startMs,
    required this.endMs,
    required this.confidence,
  });

  static Future<WordItem> default_() =>
      RustLib.instance.api.crateApiCommonWordItemDefault();

  @override
  int get hashCode =>
      text.hashCode ^ startMs.hashCode ^ endMs.hashCode ^ confidence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WordItem &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          startMs == other.startMs &&
          endMs == other.endMs &&
          confidence == other.confidence;
}
