// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `format_path_for_filter`, `get_ffprobe_path`, `parse_time_to_secs`, `probe_audio_tracks_fallback`, `run_ffmpeg_with_progress`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ProbeOutput`, `ProbeStream`, `ProbeTags`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

/// 提取音视频文件中的音频并重采样为 16kHz 单声道 PCM WAV 格式
Stream<FfmpegEvent> extractAudioFromMedia({
  required String ffmpegPath,
  required String inputPath,
  required String outputPath,
}) => RustLib.instance.api.crateApiFfmpegExtractAudioFromMedia(
  ffmpegPath: ffmpegPath,
  inputPath: inputPath,
  outputPath: outputPath,
);

/// 将 SRT 字幕文件集成到视频中（软封装或硬压制）
Stream<FfmpegEvent> muxSrtToVideo({
  required String ffmpegPath,
  required String videoPath,
  required String srtPath,
  required String outputPath,
  required bool hardBurn,
}) => RustLib.instance.api.crateApiFfmpegMuxSrtToVideo(
  ffmpegPath: ffmpegPath,
  videoPath: videoPath,
  srtPath: srtPath,
  outputPath: outputPath,
  hardBurn: hardBurn,
);

Future<List<AudioTrackInfo>> probeAudioTracks({
  required String ffmpegPath,
  required String filePath,
}) => RustLib.instance.api.crateApiFfmpegProbeAudioTracks(
  ffmpegPath: ffmpegPath,
  filePath: filePath,
);

/// 将 ISO 639-2 (三字母) 转换为 (ISO 639-1 二字母, 语言中文名称)
Future<(String, String)> convertIso6392({required String code}) =>
    RustLib.instance.api.crateApiFfmpegConvertIso6392(code: code);

class AudioTrackInfo {
  final BigInt index;
  final String codecName;
  final String? language;
  final String? title;

  const AudioTrackInfo({
    required this.index,
    required this.codecName,
    this.language,
    this.title,
  });

  @override
  int get hashCode =>
      index.hashCode ^ codecName.hashCode ^ language.hashCode ^ title.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioTrackInfo &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          codecName == other.codecName &&
          language == other.language &&
          title == other.title;
}

class FfmpegEvent {
  final int? progress;
  final String? success;
  final String? error;

  const FfmpegEvent({this.progress, this.success, this.error});

  @override
  int get hashCode => progress.hashCode ^ success.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfmpegEvent &&
          runtimeType == other.runtimeType &&
          progress == other.progress &&
          success == other.success &&
          error == other.error;
}
