// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `format_path_for_filter`

/// 提取音视频文件中的音频并重采样为 16kHz 单声道 PCM WAV 格式
Future<String> extractAudioFromMedia({
  required String ffmpegPath,
  required String inputPath,
  required String outputPath,
}) => RustLib.instance.api.crateApiFfmpegExtractAudioFromMedia(
  ffmpegPath: ffmpegPath,
  inputPath: inputPath,
  outputPath: outputPath,
);

/// 将 SRT 字幕文件集成到视频中（软封装或硬压制）
Future<String> muxSrtToVideo({
  required String ffmpegPath,
  required String videoPath,
  required String srtPath,
  required String outputPath,
  required bool hardBurn,
}) => RustLib.instance.api.crateApiFfmpegMuxSrtToVideo(
  ffmpegPath: ffmpegPath,
  videoPath: videoPath,
  srtPath: srtPath,
  outputPath: outputPath,
  hardBurn: hardBurn,
);
