// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `format_path_for_filter`, `parse_time_to_secs`, `run_ffmpeg_with_progress`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

/// 提取音视频文件中的音频并重采样为 16kHz 单声道 PCM WAV 格式
Stream<FfmpegEvent> extractAudioFromMedia({
  required String ffmpegPath,
  required String inputPath,
  required String outputPath,
}) => RustLib.instance.api.crateApiFfmpegExtractAudioFromMedia(
  ffmpegPath: ffmpegPath,
  inputPath: inputPath,
  outputPath: outputPath,
);

/// 将 SRT 字幕文件集成到视频中（软封装或硬压制）
Stream<FfmpegEvent> muxSrtToVideo({
  required String ffmpegPath,
  required String videoPath,
  required String srtPath,
  required String outputPath,
  required bool hardBurn,
}) => RustLib.instance.api.crateApiFfmpegMuxSrtToVideo(
  ffmpegPath: ffmpegPath,
  videoPath: videoPath,
  srtPath: srtPath,
  outputPath: outputPath,
  hardBurn: hardBurn,
);

class FfmpegEvent {
  final int? progress;
  final String? success;
  final String? error;

  const FfmpegEvent({this.progress, this.success, this.error});

  @override
  int get hashCode => progress.hashCode ^ success.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfmpegEvent &&
          runtimeType == other.runtimeType &&
          progress == other.progress &&
          success == other.success &&
          error == other.error;
}
