// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ModelFileManifest`, `ModelPackageManifest`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

Future<ModelInfo> validateQwenModel({required String modelDir}) =>
    RustLib.instance.api.crateApiModelsValidateQwenModel(modelDir: modelDir);

class ModelInfo {
  final String modelId;
  final String path;
  final bool valid;
  final BigInt totalSizeBytes;
  final List<String> missingFiles;

  const ModelInfo({
    required this.modelId,
    required this.path,
    required this.valid,
    required this.totalSizeBytes,
    required this.missingFiles,
  });

  @override
  int get hashCode =>
      modelId.hashCode ^
      path.hashCode ^
      valid.hashCode ^
      totalSizeBytes.hashCode ^
      missingFiles.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModelInfo &&
          runtimeType == other.runtimeType &&
          modelId == other.modelId &&
          path == other.path &&
          valid == other.valid &&
          totalSizeBytes == other.totalSizeBytes &&
          missingFiles == other.missingFiles;
}
