// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'whisper.dart';

// These functions are ignored because they are not marked as `pub`: `disable_power_throttling`, `extract_tar_gz_if_needed`, `find_silence_sequence`, `get_media_duration_secs`, `get_physical_pcore_mask`, `lock_high_priority`, `parse_duration_str`, `register_thread_as_pro_audio`, `run_stream_pipeline_inner`, `set_thread_affinity_mask`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AudioFrameState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Stream<TranscriptionEvent> transcribeStream({
  required String ffmpegPath,
  required String inputPath,
  required String modelPath,
  required String dfModelPath,
  String? language,
  required bool translate,
  int? threads,
  required bool useGpu,
  required bool toSimplified,
  required bool enableDenoise,
  required bool vadEnabled,
  required double vadThreshold,
  required int vadMinSpeechMs,
  required int vadMinSilenceMs,
}) => RustLib.instance.api.crateApiStreamPipelineTranscribeStream(
  ffmpegPath: ffmpegPath,
  inputPath: inputPath,
  modelPath: modelPath,
  dfModelPath: dfModelPath,
  language: language,
  translate: translate,
  threads: threads,
  useGpu: useGpu,
  toSimplified: toSimplified,
  enableDenoise: enableDenoise,
  vadEnabled: vadEnabled,
  vadThreshold: vadThreshold,
  vadMinSpeechMs: vadMinSpeechMs,
  vadMinSilenceMs: vadMinSilenceMs,
);
