// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../qwen/backend.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'silero_vad.dart';

// These functions are ignored because they are not marked as `pub`: `add_perf_record`, `disable_power_throttling`, `extract_tar_gz_if_needed`, `get_media_duration_secs`, `get_physical_pcore_mask`, `is_qwen_model_dir`, `join`, `lock_high_priority`, `parse_duration_str`, `run_stream_pipeline_inner`, `set_thread_affinity_mask`, `spawn_dfn_worker`, `spawn_ffmpeg_pump`, `spawn_qwen_worker`, `spawn_vad_worker`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AsrTask`, `EncodedTask`, `FfmpegPumpHandle`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `eq`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `get_or_create_qwen_runtime`
// These functions are ignored (category: IgnoreBecauseNotAllowedOwner): `add`

void setRustPerfLogging({required bool enable}) => RustLib.instance.api
    .crateApiStreamPipelineSetRustPerfLogging(enable: enable);

void unloadQwenRuntime() =>
    RustLib.instance.api.crateApiStreamPipelineUnloadQwenRuntime();

void preloadQwenModel({
  required String asrModelDir,
  String? alignerModelDir,
  String? decoderFile,
}) => RustLib.instance.api.crateApiStreamPipelinePreloadQwenModel(
  asrModelDir: asrModelDir,
  alignerModelDir: alignerModelDir,
  decoderFile: decoderFile,
);

void cancelTranscriptionBackend() =>
    RustLib.instance.api.crateApiStreamPipelineCancelTranscriptionBackend();

Stream<TranscriptionEvent> transcribeStream({required PipelineConfig config}) =>
    RustLib.instance.api.crateApiStreamPipelineTranscribeStream(config: config);

abstract class TranscriptionSink {
  Future<void> add({required TranscriptionEvent event});
}

class PipelineConfig {
  final String ffmpegPath;
  final String inputPath;
  final String modelPath;
  final String vadModelPath;
  final String dfModelPath;
  final String asrModelDir;
  final String? alignerModelDir;

  /// 解码器 GGUF 文件名 (量化选择)，如 "decoder.q4_k_m.gguf"；None 时按优先级自动扫描
  final String? decoderFile;
  final String? contextPrompt;
  final EncoderBackend encoderBackend;
  final DecoderBackend decoderBackend;
  final TimestampMode timestampMode;
  final String? language;
  final bool translate;
  final int? threads;
  final bool useGpu;
  final bool toSimplified;
  final bool noContext;
  final bool noStateHistory;
  final bool enableDenoise;
  final bool vadEnabled;
  final double vadThreshold;
  final int vadMinSpeechMs;
  final int vadMinSilenceMs;
  final BigInt? selectedAudioTrack;

  const PipelineConfig({
    required this.ffmpegPath,
    required this.inputPath,
    required this.modelPath,
    required this.vadModelPath,
    required this.dfModelPath,
    required this.asrModelDir,
    this.alignerModelDir,
    this.decoderFile,
    this.contextPrompt,
    required this.encoderBackend,
    required this.decoderBackend,
    required this.timestampMode,
    this.language,
    required this.translate,
    this.threads,
    required this.useGpu,
    required this.toSimplified,
    required this.noContext,
    required this.noStateHistory,
    required this.enableDenoise,
    required this.vadEnabled,
    required this.vadThreshold,
    required this.vadMinSpeechMs,
    required this.vadMinSilenceMs,
    this.selectedAudioTrack,
  });

  @override
  int get hashCode =>
      ffmpegPath.hashCode ^
      inputPath.hashCode ^
      modelPath.hashCode ^
      vadModelPath.hashCode ^
      dfModelPath.hashCode ^
      asrModelDir.hashCode ^
      alignerModelDir.hashCode ^
      decoderFile.hashCode ^
      contextPrompt.hashCode ^
      encoderBackend.hashCode ^
      decoderBackend.hashCode ^
      timestampMode.hashCode ^
      language.hashCode ^
      translate.hashCode ^
      threads.hashCode ^
      useGpu.hashCode ^
      toSimplified.hashCode ^
      noContext.hashCode ^
      noStateHistory.hashCode ^
      enableDenoise.hashCode ^
      vadEnabled.hashCode ^
      vadThreshold.hashCode ^
      vadMinSpeechMs.hashCode ^
      vadMinSilenceMs.hashCode ^
      selectedAudioTrack.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PipelineConfig &&
          runtimeType == other.runtimeType &&
          ffmpegPath == other.ffmpegPath &&
          inputPath == other.inputPath &&
          modelPath == other.modelPath &&
          vadModelPath == other.vadModelPath &&
          dfModelPath == other.dfModelPath &&
          asrModelDir == other.asrModelDir &&
          alignerModelDir == other.alignerModelDir &&
          decoderFile == other.decoderFile &&
          contextPrompt == other.contextPrompt &&
          encoderBackend == other.encoderBackend &&
          decoderBackend == other.decoderBackend &&
          timestampMode == other.timestampMode &&
          language == other.language &&
          translate == other.translate &&
          threads == other.threads &&
          useGpu == other.useGpu &&
          toSimplified == other.toSimplified &&
          noContext == other.noContext &&
          noStateHistory == other.noStateHistory &&
          enableDenoise == other.enableDenoise &&
          vadEnabled == other.vadEnabled &&
          vadThreshold == other.vadThreshold &&
          vadMinSpeechMs == other.vadMinSpeechMs &&
          vadMinSilenceMs == other.vadMinSilenceMs &&
          selectedAudioTrack == other.selectedAudioTrack;
}

enum TimestampMode { fast, precise }
