// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'common.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `boundary_cost`, `classify_period_word`, `count_units`, `is_cjk_char`, `is_comma_punct`, `is_leadin_comma_boundary`, `is_punct_boundary`, `is_real_period`, `is_strong_punct`, `is_weak_punct`, `is_western_word_char`, `is_word_internal_boundary`, `mid_sentence_cost`, `segment_cost`, `strong_punct_boundary`, `strong_punct_end`, `weak_punct_end`

/// 移除文本中所有的全角句号 "。"
Future<String> removePeriods({required String text}) =>
    RustLib.instance.api.crateApiSubtitleSplitRemovePeriods(text: text);

/// 将一段带标点文本及其词/字级时间戳拆成 2~5 秒的字幕 (动态规划)。
///
/// - `units` 为空时返回空 Vec, 调用方回退为整段一条字幕;
/// - 拆分点优先落在句末标点/长停顿, 其次句中逗号, 无标点按时长硬切;
/// - 输出字幕的时间已做轻微视觉平滑且保证相邻不重叠:
///   平滑重叠时 (上一句尾垫吞掉本句头垫) 在两句真实时间边界之间取中点,
///   上一句回缩尾垫, 保证本句字幕不晚于其语音起点出现;
/// - `quality` 为对齐质量标记 (如 "ForcedAligned"/"LinearFallback"),
///   透传到输出字幕, 使 UI/SRT 能区分真实对齐与线性回退;
/// - `block_start_ms`/`block_end_ms` 为块的真实媒体边界:
///   平滑前垫/后延以此为 clamp 上下限, 保证块内首条/末条字幕
///   与其余字幕的平滑行为一致, 避免块起点/大停顿后出现整体跳变。
Future<List<TranscriptionSegment>> splitSubtitles({
  required List<WordItem> units,
  required String quality,
  required PlatformInt64 blockStartMs,
  required PlatformInt64 blockEndMs,
}) => RustLib.instance.api.crateApiSubtitleSplitSplitSubtitles(
  units: units,
  quality: quality,
  blockStartMs: blockStartMs,
  blockEndMs: blockEndMs,
);
