// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `compute_with_scale`, `compute`, `decision_to_segment`, `detect`, `extend_speech`, `fix_smooth_window_start`, `load`, `mel_scale`, `merge_short_silence`, `new`, `parse_kaldi_cmvn`, `process`, `smooth_preds_with_state_machine`, `smooth_prob`, `split_long_speech`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FireVadEngine`, `KaldiFbank`, `VadPostprocessor`, `VadSegment`, `VadState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

class FireVadConfig {
  final BigInt smoothWindowSize;
  final double threshold;
  final BigInt minSpeechFrame;
  final BigInt maxSpeechFrame;
  final BigInt minSilenceFrame;
  final BigInt mergeSilenceFrame;
  final BigInt extendSpeechFrame;

  const FireVadConfig({
    required this.smoothWindowSize,
    required this.threshold,
    required this.minSpeechFrame,
    required this.maxSpeechFrame,
    required this.minSilenceFrame,
    required this.mergeSilenceFrame,
    required this.extendSpeechFrame,
  });

  static Future<FireVadConfig> default_() =>
      RustLib.instance.api.crateApiVadFireVadConfigDefault();

  @override
  int get hashCode =>
      smoothWindowSize.hashCode ^
      threshold.hashCode ^
      minSpeechFrame.hashCode ^
      maxSpeechFrame.hashCode ^
      minSilenceFrame.hashCode ^
      mergeSilenceFrame.hashCode ^
      extendSpeechFrame.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FireVadConfig &&
          runtimeType == other.runtimeType &&
          smoothWindowSize == other.smoothWindowSize &&
          threshold == other.threshold &&
          minSpeechFrame == other.minSpeechFrame &&
          maxSpeechFrame == other.maxSpeechFrame &&
          minSilenceFrame == other.minSilenceFrame &&
          mergeSilenceFrame == other.mergeSilenceFrame &&
          extendSpeechFrame == other.extendSpeechFrame;
}
