// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'whisper.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `clean_punctuation_and_whitespace`, `deduplicate_phrases`, `deduplicate_repeats`, `energy_based_vad`, `get_or_create_context`, `has_repetition_loop`, `post_process_segments`, `progress_callback_trampoline`, `run_transcription_inner`, `split_long_segments`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CachedContext`, `ProgressContext`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

Future<HardwareAccelerationInfo> getHardwareAccelerationInfo() =>
    RustLib.instance.api.crateApiWhisperGetHardwareAccelerationInfo();

Future<String> convertChinese({
  required String text,
  required bool toSimplified,
}) => RustLib.instance.api.crateApiWhisperConvertChinese(
  text: text,
  toSimplified: toSimplified,
);

Future<List<String>> convertChineseList({
  required List<String> texts,
  required bool toSimplified,
}) => RustLib.instance.api.crateApiWhisperConvertChineseList(
  texts: texts,
  toSimplified: toSimplified,
);

Stream<TranscriptionEvent> transcribe({
  required String modelPath,
  required String audioPath,
  String? language,
  required bool translate,
  int? threads,
  required bool useGpu,
  required bool vadEnabled,
  required double vadThreshold,
  required int vadMinSpeechMs,
  required int vadMinSilenceMs,
  required double temperature,
  required double temperatureInc,
  required double entropyThold,
  required double logprobThold,
  required double noSpeechThold,
  required bool noContext,
}) => RustLib.instance.api.crateApiWhisperTranscribe(
  modelPath: modelPath,
  audioPath: audioPath,
  language: language,
  translate: translate,
  threads: threads,
  useGpu: useGpu,
  vadEnabled: vadEnabled,
  vadThreshold: vadThreshold,
  vadMinSpeechMs: vadMinSpeechMs,
  vadMinSilenceMs: vadMinSilenceMs,
  temperature: temperature,
  temperatureInc: temperatureInc,
  entropyThold: entropyThold,
  logprobThold: logprobThold,
  noSpeechThold: noSpeechThold,
  noContext: noContext,
);

class HardwareAccelerationInfo {
  final bool isVulkanAvailable;
  final List<VulkanDeviceInfo> devices;

  const HardwareAccelerationInfo({
    required this.isVulkanAvailable,
    required this.devices,
  });

  static Future<HardwareAccelerationInfo> default_() =>
      RustLib.instance.api.crateApiWhisperHardwareAccelerationInfoDefault();

  @override
  int get hashCode => isVulkanAvailable.hashCode ^ devices.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HardwareAccelerationInfo &&
          runtimeType == other.runtimeType &&
          isVulkanAvailable == other.isVulkanAvailable &&
          devices == other.devices;
}

@freezed
sealed class TranscriptionEvent with _$TranscriptionEvent {
  const TranscriptionEvent._();

  const factory TranscriptionEvent.progress(int field0) =
      TranscriptionEvent_Progress;
  const factory TranscriptionEvent.success(List<TranscriptionSegment> field0) =
      TranscriptionEvent_Success;
  const factory TranscriptionEvent.failure(String field0) =
      TranscriptionEvent_Failure;
}

class TranscriptionSegment {
  final PlatformInt64 startMs;
  final PlatformInt64 endMs;
  final String text;

  const TranscriptionSegment({
    required this.startMs,
    required this.endMs,
    required this.text,
  });

  static Future<TranscriptionSegment> default_() =>
      RustLib.instance.api.crateApiWhisperTranscriptionSegmentDefault();

  @override
  int get hashCode => startMs.hashCode ^ endMs.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TranscriptionSegment &&
          runtimeType == other.runtimeType &&
          startMs == other.startMs &&
          endMs == other.endMs &&
          text == other.text;
}

class VulkanDeviceInfo {
  final int id;
  final String name;
  final BigInt totalVramBytes;

  const VulkanDeviceInfo({
    required this.id,
    required this.name,
    required this.totalVramBytes,
  });

  static Future<VulkanDeviceInfo> default_() =>
      RustLib.instance.api.crateApiWhisperVulkanDeviceInfoDefault();

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ totalVramBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VulkanDeviceInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          totalVramBytes == other.totalVramBytes;
}
