// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'whisper.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `progress_callback_trampoline`, `run_transcription`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Stream<TranscriptionEvent> transcribe({
  required String modelPath,
  required String audioPath,
  String? language,
  required bool translate,
  int? threads,
  required bool useGpu,
}) => RustLib.instance.api.crateApiWhisperTranscribe(
  modelPath: modelPath,
  audioPath: audioPath,
  language: language,
  translate: translate,
  threads: threads,
  useGpu: useGpu,
);

@freezed
sealed class TranscriptionEvent with _$TranscriptionEvent {
  const TranscriptionEvent._();

  const factory TranscriptionEvent.progress(int field0) =
      TranscriptionEvent_Progress;
  const factory TranscriptionEvent.success(List<TranscriptionSegment> field0) =
      TranscriptionEvent_Success;
  const factory TranscriptionEvent.failure(String field0) =
      TranscriptionEvent_Failure;
}

class TranscriptionSegment {
  final PlatformInt64 startMs;
  final PlatformInt64 endMs;
  final String text;

  const TranscriptionSegment({
    required this.startMs,
    required this.endMs,
    required this.text,
  });

  static Future<TranscriptionSegment> default_() =>
      RustLib.instance.api.crateApiWhisperTranscriptionSegmentDefault();

  @override
  int get hashCode => startMs.hashCode ^ endMs.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TranscriptionSegment &&
          runtimeType == other.runtimeType &&
          startMs == other.startMs &&
          endMs == other.endMs &&
          text == other.text;
}
