// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'whisper.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `calculate_rms`, `decode_tokens`, `get_num_mel_bins`, `get_or_create_context`, `get_prompt_tokens`, `get_unicode_to_bytes`, `load_vocabulary`, `parse_json_vocabulary`, `parse_tokens_to_segments`, `payout_or_default`, `register_thread_as_pro_audio`, `run_ort_vad_with_session`, `run_ort_vad_with_state`, `run_ort_vad`, `run_transcription_inner`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CachedContext`, `WhisperModel`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Future<String> convertChinese({
  required String text,
  required bool toSimplified,
}) => RustLib.instance.api.crateApiWhisperConvertChinese(
  text: text,
  toSimplified: toSimplified,
);

Future<List<String>> convertChineseList({
  required List<String> texts,
  required bool toSimplified,
}) => RustLib.instance.api.crateApiWhisperConvertChineseList(
  texts: texts,
  toSimplified: toSimplified,
);

Stream<TranscriptionEvent> transcribe({
  required String modelPath,
  required String vadModelPath,
  required String audioPath,
  String? language,
  required bool translate,
  int? threads,
  required bool useGpu,
  required bool vadEnabled,
  required double vadThreshold,
  required int vadMinSpeechMs,
  required int vadMinSilenceMs,
  required double temperature,
  required double temperatureInc,
  required double entropyThold,
  required double logprobThold,
  required double noSpeechThold,
  required bool noContext,
  required bool noStateHistory,
}) => RustLib.instance.api.crateApiWhisperTranscribe(
  modelPath: modelPath,
  vadModelPath: vadModelPath,
  audioPath: audioPath,
  language: language,
  translate: translate,
  threads: threads,
  useGpu: useGpu,
  vadEnabled: vadEnabled,
  vadThreshold: vadThreshold,
  vadMinSpeechMs: vadMinSpeechMs,
  vadMinSilenceMs: vadMinSilenceMs,
  temperature: temperature,
  temperatureInc: temperatureInc,
  entropyThold: entropyThold,
  logprobThold: logprobThold,
  noSpeechThold: noSpeechThold,
  noContext: noContext,
  noStateHistory: noStateHistory,
);

Future<void> warmupWhisperContext({
  required String modelPath,
  required bool useGpu,
  required double totalDuration,
}) => RustLib.instance.api.crateApiWhisperWarmupWhisperContext(
  modelPath: modelPath,
  useGpu: useGpu,
  totalDuration: totalDuration,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VadSessionState>>
abstract class VadSessionState implements RustOpaqueInterface {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<VadSessionState> newInstance() =>
      RustLib.instance.api.crateApiWhisperVadSessionStateNew();

  Future<void> reset();

  Future<void> shift({required BigInt offset});
}

@freezed
sealed class TranscriptionEvent with _$TranscriptionEvent {
  const TranscriptionEvent._();

  const factory TranscriptionEvent.progress(int field0) =
      TranscriptionEvent_Progress;
  const factory TranscriptionEvent.progressDetail({
    required PlatformInt64 processedMs,
    required PlatformInt64 totalMs,
  }) = TranscriptionEvent_ProgressDetail;
  const factory TranscriptionEvent.success(List<TranscriptionSegment> field0) =
      TranscriptionEvent_Success;
  const factory TranscriptionEvent.failure(String field0) =
      TranscriptionEvent_Failure;
  const factory TranscriptionEvent.segment(TranscriptionSegment field0) =
      TranscriptionEvent_Segment;
}

class TranscriptionSegment {
  final PlatformInt64 startMs;
  final PlatformInt64 endMs;
  final String text;

  const TranscriptionSegment({
    required this.startMs,
    required this.endMs,
    required this.text,
  });

  static Future<TranscriptionSegment> default_() =>
      RustLib.instance.api.crateApiWhisperTranscriptionSegmentDefault();

  @override
  int get hashCode => startMs.hashCode ^ endMs.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TranscriptionSegment &&
          runtimeType == other.runtimeType &&
          startMs == other.startMs &&
          endMs == other.endMs &&
          text == other.text;
}
